### ISSUE TITLE
uvicorn 0.2: NameError under pypy

### ISSUE THREAD

**Issue by extraymond** [Kludex/uvicorn#104]
## system info

**os specification**: ubuntu 18.04 64bit
**python version**: pypy3-5-6.0.0(pyenv)
**uvicorn version**: 0.2.2(via poetry)

### case1: launching source file as module

expected behavior: When launch an asgi app (apistar) via scipt, uvicorn should be able to launch it.

**error log:**

```python
/home/user/.pyenv/versions/pypy3.5-6.0.0/lib-python/3/importlib/_bootstrap.py:223: UserWarning: builtins.type size changed, may indicate binary incompatibility. Expected 872, got 416
  return f(*args, **kwds)
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/pypy3.5-6.0.0/envs/vr_info/site-packages/uvicorn/main.py", line 74, in load_app
    module = importlib.import_module(module_str)
  File "/home/user/.pyenv/versions/pypy3.5-6.0.0/lib-python/3/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 987, in _gcd_import
  File "<frozen importlib._bootstrap>", line 970, in _find_and_load
  File "<frozen importlib._bootstrap>", line 945, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 223, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 987, in _gcd_import
  File "<frozen importlib._bootstrap>", line 970, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
ImportError: No module named 'vr_info'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.pyenv/versions/vr_info/bin/uvicorn", line 11, in <module>
    load_entry_point('uvicorn==0.2.2', 'console_scripts', 'uvicorn')()
  File "/home/user/.pyenv/versions/pypy3.5-6.0.0/envs/vr_info/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/.pyenv/versions/pypy3.5-6.0.0/envs/vr_info/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/user/.pyenv/versions/pypy3.5-6.0.0/envs/vr_info/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/.pyenv/versions/pypy3.5-6.0.0/envs/vr_info/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/user/.pyenv/versions/pypy3.5-6.0.0/envs/vr_info/site-packages/uvicorn/main.py", line 37, in main
    app = load_app(app)
  File "/home/user/.pyenv/versions/pypy3.5-6.0.0/envs/vr_info/site-packages/uvicorn/main.py", line 75, in load_app
    except ModuleNotFoundError:
NameError: name 'ModuleNotFoundError' is not defined

```

It states that my package vr_info is not installed, but daphne can launch it just fine.

```shell
daphne vr_info.main:app
2018-06-29 21:08:20,210 INFO     Starting server at tcp:port=8000:interface=127.0.0.1
2018-06-29 21:08:20,212 INFO     HTTP/2 support enabled
2018-06-29 21:08:20,212 INFO     Configuring endpoint tcp:port=8000:interface=127.0.0.1
2018-06-29 21:08:20,214 INFO     Listening on TCP address 127.0.0.1:8000

```

### case2: build source into package and launch it via the module

**expected behavior**: When launch an asgi app (apistar) via package module, uvicorn should be able to launch it.

**error log**:

```python
home/user/.pyenv/versions/pypy3.5-6.0.0/lib-python/3/importlib/_bootstrap.py:223: UserWarning: builtins.type size changed, may indicate binary incompatibility. Expected 872, got 416
  return f(*args, **kwds)
ERROR: 'NoneType' object is not iterable
```

My wild guess would be pypy(based on 3.5) not supporting async generators with __aiter__ and __anext__.

Will try to bisect with cpython later.

---

Edit:

- cpython works just fine.

**Comment by lovelydinosaur** [comment]
Are you using ‘—loop asnycio —http h11’?

You’ll need to do that to get a pure Python implementation.

(We should probably raise an error if using uvloop/httptools under PyPy to make this explicit)

**Comment by extraymond** [comment]
Thx for your reply! It's working with those arguments you mentioned.

I got the impression from the uvloop dev that uvloop is not really helpful under pypy, hence it's not really on his mind to support it. Thx for making uvcorn compatible without it. Everything pypy compatible is awesome in my book!

Results are that it's still faster than daphne! 6.2K/req vs 2.9K/reg, up to 100% faster.
