### ISSUE TITLE
WARNING: Invalid HTTP request received.                  Only when running GET request from inside of Excel

### ISSUE THREAD

**Issue by rag5495** [Kludex/uvicorn#1093]
I am trying to write an Excel addin that uses node.js to make a GET request to a fastapi/uvicorn server on localhost. Below is the function I wrote:
```
function getData() {
    //You can change this URL to any web request you want to work with.
    const http = require('http');
    const options = {
      hostname: 'localhost',
      port: 8000,
      path: '/1/2/3/4',
      method: 'GET'
    };

    const req = http.request(options, res => {
      res.on('data', d => {
        process.stdout.write(d)
      })
    })
    req.on('error', error => {
      console.error(error)
    })

    req.end()
}
```
If I run this in a terminal with node, it runs fine and shows a 200 response on the server. If I try running the function from within Excel as a UDF, it displays 0 in the cell and the server gives the following traceback:

```
WARNING:  Invalid HTTP request received.
Traceback (most recent call last):
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 172, in handle_events
    event = self.conn.next_event()
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/h11/_connection.py", line 443, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
    raise self
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/h11/_readers.py", line 72, in maybe_read_from_IDLE_client
    matches = validate(
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/h11/_util.py", line 88, in validate
    raise LocalProtocolError(msg)
h11._util.RemoteProtocolError: illegal request line: bytearray(b'\x16\x03\x01\x02\x00\x01\x00\x01\xfc\x03\x03\xb2vs;\xdaP\xfb[\x17o\xbb\x9d:>\x12@\xe2\xd8\xae\xfa5H\x0e\xac\xb9"d\xe8\x89\xd4No  \xb2\x98\xb5\xd9\xe5\x93?\xdeT\xbf\xa5Q\xf4\xac9\x19\x81?]\x05\x14\x1at\xf5\xca\xde\xbd\xea\xa2\xe7l\x008')
WARNING:  Invalid HTTP request received.
Traceback (most recent call last):
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 172, in handle_events
    event = self.conn.next_event()
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/h11/_connection.py", line 443, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
    raise self
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/Users/rgodbey/Desktop/spade/venv/lib/python3.8/site-packages/h11/_readers.py", line 68, in maybe_read_from_IDLE_client
    raise LocalProtocolError("illegal request line")
h11._util.RemoteProtocolError: illegal request line
```

My thought is that somehow Excel is doing something to the GET request. Any help in debugging this is appreciated! I am unsure how to log the GET request so I can see what is happening.

**Comment by euri10** [comment]
I'd start with checking if you get the same with httptools

**Comment by f11r** [comment]
We ran into a similar problem and for us it was having a non-escaped space in the URL query parameters (e.g. `google.com?q=first second` instead of `google.com?q=first%20second`). It would be great if uvicorn handled this in a non-5XX way. But I'm not familiar enough with the web standards to know whether this is supposed to be a 4XX or a 200.

**Comment by euri10** [comment]
what's the traceback you get ?
you cant get spaces in urls

**Comment by f11r** [comment]
```
WARNING:  Invalid HTTP request received.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 136, in handle_events
    event = self.conn.next_event()
  File "/usr/local/lib/python3.9/site-packages/h11/_connection.py", line 443, in next_event
    exc._reraise_as_remote_protocol_error()
  File "/usr/local/lib/python3.9/site-packages/h11/_util.py", line 76, in _reraise_as_remote_protocol_error
    raise self
  File "/usr/local/lib/python3.9/site-packages/h11/_connection.py", line 425, in next_event
    event = self._extract_next_receive_event()
  File "/usr/local/lib/python3.9/site-packages/h11/_connection.py", line 367, in _extract_next_receive_event
    event = self._reader(self._receive_buffer)
  File "/usr/local/lib/python3.9/site-packages/h11/_readers.py", line 72, in maybe_read_from_IDLE_client
    matches = validate(
  File "/usr/local/lib/python3.9/site-packages/h11/_util.py", line 88, in validate
    raise LocalProtocolError(msg)
h11._util.RemoteProtocolError: illegal request line: bytearray(b'GET /teams?q=fc G HTTP/1.1')
```

Everything worked once we had the client escape the space in the URL (`/teams?g=fc%20G`).

**Comment by euri10** [comment]
looks like it's the way to go, not sure there's something actionnable on our side, would be interesting to see if we have the same running with httptools instead of h11 though

**Comment by bertramr** [comment]
Yes, same is happening for httptools. Error traceback is a bit different.

**Comment by lovelydinosaur** [comment]
So, you're getting a warning that it's attempted to handle an invalid HTTP request.
Because it was sent an invalid HTTP request.

> Everything worked once we had the client escape the space in the URL (/teams?g=fc%20G).

Exactly.

You've got a broken client. The server's doing the right thing here.

**Comment by f11r** [comment]
> You've got a broken client.

100% agree.

> The server's doing the right thing here.

I disagree here. I think the right thing to do for the server would be to return a 4XX, not 5XX, since, as you mentioned, the client is broken. Returning a 5XX suggests to the client that what they're doing is fine.

**Comment by bertramr** [comment]
100% agree with you both. When I looked into it, it appears that uvicorn just returns an empty response without status and in my case the nginx proxy makes this a 502.  But I'm still not sure, whether uvicorn (or the http parser) should make it a 4xx.

**Comment by Kludex** [comment]
Yeah, this was brought upon https://github.com/encode/uvicorn/pull/205
