### ISSUE TITLE
hot reload doesnt work when using uvicorn programatially using the Config class

### ISSUE THREAD

**Issue by nbraun-wolf** [Kludex/uvicorn#1204]
### Describe the bug

Hi, I am trying to set up logging for a uvicorn/fastapi app. I have followed this [blogpost](https://pawamoy.github.io/posts/unify-logging-for-a-gunicorn-uvicorn-app/). I want to enable hot reload for development, but it isn't used, despite unicorn logging at the beginning that it's watching for file changes.

### To reproduce

```python
from uvicorn import Config, Server

server = Server(
    Config(
        "main:create_app",
        factory=True,
        host="0.0.0.0",
        port=8080
        reload=True,
    ),
)

server.run()
# same issue with:
# uvicorn.run(Config(...))
```

### Expected behaviour

hot reload works when using the reload kwarg in the Config class.

### Actual behaviour

Hot reload does not work.

### Environment

```bash
Running uvicorn 0.15.0 with CPython 3.9.7 on Linux
```

**Comment by Kludex** [comment]
The error message is misleading. But the right way to use reload in code is documented.

![image](https://user-images.githubusercontent.com/7353520/135708899-a3a7c535-1b6b-4a74-b1a6-28a3d62c2c8d.png)

**Comment by Kludex** [comment]
btw, next time you open an issue here, write an example that people can reproduce without any effort, please. 

Also. "Hot reload does not work." is not the actual behavior, the actual behavior is this:

I run the code and I get this traceback:
```bash
Traceback (most recent call last):
  File "/home/marcelo/anaconda3/bin/uvicorn", line 33, in <module>
    sys.exit(load_entry_point('uvicorn', 'console_scripts', 'uvicorn')())
  File "/home/marcelo/anaconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/marcelo/anaconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/marcelo/anaconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/marcelo/anaconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/marcelo/Development/encode/uvicorn/uvicorn/main.py", line 425, in main
    run(app, **kwargs)
  File "/home/marcelo/Development/encode/uvicorn/uvicorn/main.py", line 448, in run
    server.run()
  File "/home/marcelo/Development/encode/uvicorn/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/marcelo/anaconda3/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1501, in uvloop.loop.Loop.run_until_complete
  File "/home/marcelo/Development/encode/uvicorn/uvicorn/server.py", line 76, in serve
    config.load()
  File "/home/marcelo/Development/encode/uvicorn/uvicorn/config.py", line 448, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/marcelo/Development/encode/uvicorn/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/marcelo/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 22, in <module>
    uvicorn.run(config)
  File "/home/marcelo/Development/encode/uvicorn/uvicorn/main.py", line 448, in run
    server.run()
  File "/home/marcelo/Development/encode/uvicorn/uvicorn/server.py", line 68, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/marcelo/anaconda3/lib/python3.8/asyncio/runners.py", line 33, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine 'Server.serve' was never awaited
```

**Comment by nbraun-wolf** [comment]
I had the piece there, I just forgot to include it here. It is starting up when having, but its not reloading. Please dont close this without clarification. Or should I now open a new issue? It is in fact not working. There is a reason the config is generated first. Please refer to the blogpost.

```python
if __name__ == '__main__':
    server = Server(
        Config(
            "my_app.app:app",
            host="0.0.0.0",
            log_level=LOG_LEVEL,
        ),
    )

    # setup logging last, to make sure no library overwrites it
    # (they shouldn't, but it happens)
    setup_logging()

    server.run()
```


Sorry that I forgot to include that.  No need to get sassy.
