### ISSUE TITLE
Proxy errors due to improper inference of `websockets` version (based on Python version)

### ISSUE THREAD

**Issue by iCalculated** [Kludex/uvicorn#1320]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

**With Python >= 3.7 and `websockets`<10, `websockets` is passed a logger parameter that the legacy server does not support.**

The `_LoggerMixin` class is required to prevent the logger from being passed into the legacy server that `websockets` uses in earlier (<10) versions. Not having the mixin yields the following error:
```
Fatal error: protocol.data_received() call failed.
protocol: <uvicorn.protocols.http.h11_impl.H11Protocol object at 0x104daa910>
transport: <_SelectorSocketTransport fd=22 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/shy/.pyenv/versions/3.9.6/lib/python3.9/asyncio/selector_events.py", line 870, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/shy/Projects/nftychat/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 131, in data_received
    self.handle_events()
  File "/Users/shy/Projects/nftychat/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 180, in handle_events
    self.handle_upgrade(event)
  File "/Users/shy/Projects/nftychat/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 268, in handle_upgrade
    protocol = self.ws_protocol_class(
  File "/Users/shy/Projects/nftychat/venv/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 77, in __init__
    super().__init__(
  File "/Users/shy/Projects/nftychat/venv/lib/python3.9/site-packages/websockets/legacy/server.py", line 201, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'logger'
```

which results in errors proxying sockets on the frontend:
```
Proxy error: Could not proxy request /socket.io/?EIO=4&transport=polling&t=NvBQjFH from localhost:3000 to http://127.0.0.1:8080/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED).
```

The class is implemented in `/uvicorn/protocols/websockets/websockets_impl.py` and infers the version of websockets from the Python version. Websockets conforms to PEP8's `__version__` so that could be used instead.

```python
# special case logger kwarg in websockets >=10
if sys.version_info >= (3, 7):
    class _LoggerMixin:
        pass
else:
    class _LoggerMixin:
        def __init__(self, *args, logger, **kwargs):
            super().__init__(*args, **kwargs)
            self.logger = logging.LoggerAdapter(logger, {"websocket": self})
```

### Steps to reproduce the bug

Dependencies:

```
uvicorn==16.0.0
websockets==0.9.1
fastapi==0.70.1
```

This fails:

```python
from fastapi import FastAPI, WebSocket
from fastapi.responses import HTMLResponse

app = FastAPI()

html = """
<script>
    var ws = new WebSocket("ws://localhost:8000/ws");
</script>
"""

@app.get("/")
async def get():
    return HTMLResponse(html)

@app.websocket("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    while True:
        data = await websocket.receive_text()
        await websocket.send_text(f"Message text was: {data}")
```

### Expected behavior

Establishing a connection successfully. 

### Actual behavior

Pretty much the same error:
```
Fatal error: protocol.data_received() call failed.
protocol: <uvicorn.protocols.http.h11_impl.H11Protocol object at 0x1067ffc70>
transport: <_SelectorSocketTransport fd=12 read=polling write=<idle, bufsize=0>>
Traceback (most recent call last):
  File "/Users/shy/.pyenv/versions/3.9.6/lib/python3.9/asyncio/selector_events.py", line 870, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/Users/shy/Projects/nftychat/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 131, in data_received
    self.handle_events()
  File "/Users/shy/Projects/nftychat/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 180, in handle_events
    self.handle_upgrade(event)
  File "/Users/shy/Projects/nftychat/venv/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 268, in handle_upgrade
    protocol = self.ws_protocol_class(
  File "/Users/shy/Projects/nftychat/venv/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 77, in __init__
    super().__init__(
  File "/Users/shy/Projects/nftychat/venv/lib/python3.9/site-packages/websockets/legacy/server.py", line 201, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'logger'
```

### Environment

Uvicorn 0.16.0, CPython 3.9.6

`uvicorn example:app` fails with the prior snippet.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/29362131/149038768-807fd357-236a-416d-877a-257570a693d5.png">

### Additional context

I'm going to make a PR using the dunder.

**Comment by Kludex** [comment]
We've bumped `websockets` for the next release ([>= 10.0](https://github.com/encode/uvicorn/blob/c6a7db5682e8f39c81bd1e59ce64555a02115a67/setup.py#L55)).

I guess this issue doesn't make sense considering that?

**Comment by iCalculated** [comment]
Yes, that will resolve the issue.

**Comment by alamorre** [comment]
When is the next release i.e. patch coming out? Running into the same issue

**Comment by Kludex** [comment]
Well... It was already released.

**Comment by olzhasar** [comment]
Even though this issue was partially resolved by bumping `websockets` version, it's still a problem for projects that cannot use newer `websockets` version because of other dependencies.
How about using the `websockets` version as @iCalculated suggested to fully resolve the issue?

**Comment by cucupac** [comment]
`EDIT:` I updated python on my machine. Doing this, with the same dependencies below, solved the issue. The web socket now works as intended.

`BEFORE EDIT:` I'm getting the exact same error with the following dependencies. Has anyone resolved this issue yet? If so, what's the solution? @iCalculated

```
anyio==3.6.2
click==8.1.3
fastapi==0.88.0
h11==0.14.0
httptools==0.5.0
idna==3.4
pydantic==1.10.4
python-dotenv==0.21.0
PyYAML==6.0
sniffio==1.3.0
starlette==0.22.0
typing_extensions==4.4.0
uvicorn==0.20.0
uvloop==0.17.0
watchfiles==0.18.1
websockets==10.4
```
