### ISSUE TITLE
Uvicorn logging error when port is a string although the server is running

### ISSUE THREAD

**Issue by uripeled2** [Kludex/uvicorn#1368]
### Checklist

- [X] The bug is reproducible against the latest release or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

If you use uvicorn.run and enter the port as string:
`uvicorn.run(app=app, host="localhost", port="3000")`

the server will still run but the logger will raise: 

> TypeError: %d format: a number is required, not str

### Steps to reproduce the bug

```
import uvicorn


async def app(scope, receive, send):
    assert scope['type'] == 'http'

    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ],
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })

uvicorn.run(app=app, host="localhost", port="3000")

```

### Expected behavior

> INFO:     Uvicorn running on http://localhost:3000 (Press CTRL+C to quit)

### Actual behavior

> TypeError: %d format: a number is required, not str

### Debugging material

INFO:     Started server process [9761]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
--- Logging error ---
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: %d format: a number is required, not str
Call stack:
  File "/Users/uri/PycharmProjects/PokemonFetcher/try.py", line 18, in <module>
    uvicorn.run(app=app, host="localhost", port="3000")
  File "/Users/uri/PycharmProjects/PokemonFetcher/venv/lib/python3.9/site-packages/uvicorn/main.py", line 461, in run
    server.run()
  File "/Users/uri/PycharmProjects/PokemonFetcher/venv/lib/python3.9/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/uri/PycharmProjects/PokemonFetcher/venv/lib/python3.9/site-packages/uvicorn/server.py", line 77, in serve
    await self.startup(sockets=sockets)
  File "/Users/uri/PycharmProjects/PokemonFetcher/venv/lib/python3.9/site-packages/uvicorn/server.py", line 165, in startup
    self._log_started_message(listeners)
  File "/Users/uri/PycharmProjects/PokemonFetcher/venv/lib/python3.9/site-packages/uvicorn/server.py", line 206, in _log_started_message
    logger.info(
Message: 'Uvicorn running on %s://%s:%d (Press CTRL+C to quit)'
Arguments: ('http', 'localhost', '3000')

### Environment

MacOS,  Python 3.9.9 , uvicorn 0.17.4

### Additional context

My proposal for solving this is to open the file uvicorn.server and go to Server. _log_started_message and to change line 195 from:
`port = config.port` to `port = int(config.port)`

I test it locally and it is working, see pull request: https://github.com/encode/uvicorn/pull/1369

If the port isn't valid this line will never get called, the problem here isn’t with the port validation or with the server startup it is just with the logger.

**Comment by lovelydinosaur** [comment]
Don't do that. 🤷‍♂️

**Comment by lovelydinosaur** [comment]
So.... at the moment my preference would be for us to close this one off.

The resolution to this is to treat the port as an integer, as intended.

```python
uvicorn.run(app=app, host="localhost", port=3000)
```

Granted, it'd be a marginal improvement if setting the port to a string raised a type error (or just worked seamlessly). And yes, it'd arguably be a marginal improvement if `run` was type-annotated.

But... this is python. It's duck typed on the whole and there's *all sorts of places everywhere throughout the entire ecosystem* where you'll get niggly behaviour if you pass the wrong type to a function.

I think we *could* consider stricter type error raising / annotating for `uvicorn`'s `run()` function, but I'm not in any rush for us to do so. For right now I'd rather we try to minimise code churn as much as possible, and focus solely on stability, and dealing with any hard-and-fast bugs, rather than UX improvements.
