### ISSUE TITLE
websocket Socketio ASGI type error :__init__() got an unexpected keyword argument 'logger' 

### ISSUE THREAD

**Issue by damyanov** [Kludex/uvicorn#1592]
The following sniped rises type error after version 0.15.0
(with 0.15 or lower all is fine..)
```
import socketio

sio = socketio.AsyncServer(async_mode='asgi',cors_allowed_origins=[])
app = socketio.ASGIApp(sio)


@sio.event
async def connect(sid, environ):
    print(sid, 'connected')

@sio.event
async def disconnect(sid):
    print(sid, 'disconnected')
```
```
Traceback (most recent call last):
  File "uvloop/handles/stream.pyx", line 829, in uvloop.loop.__uv_stream_on_read_impl
  File "uvloop/loop.pyx", line 107, in uvloop.loop.run_in_context1
  File "/root/.pyenv/versions/3.9.2/envs/c1/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 160, in data_received
    self.handle_upgrade()
  File "/root/.pyenv/versions/3.9.2/envs/c1/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 189, in handle_upgrade
    protocol = self.ws_protocol_class(  # type: ignore[call-arg]
  File "/root/.pyenv/versions/3.9.2/envs/c1/lib/python3.9/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 62, in __init__
    super().__init__(
  File "/root/.pyenv/versions/3.9.2/envs/c1/lib/python3.9/site-packages/websockets/legacy/server.py", line 201, in __init__
    super().__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'logger'
```

**Comment by Kludex** [comment]
Did you try with uvicorn 0.18.2?

What's the websockets version? Is it the latest?

**Comment by damyanov** [comment]
> Did you try with uvicorn 0.18.2?
> 
> What's the websockets version? Is it the latest?

Yes, same error with 0.18.2(websockets version - 9.1)
....

After updating websockets to the latest version(10.3) the error no longer occurs.

**Comment by Kludex** [comment]
> After updating websockets to the latest version(10.3) the error no longer occurs.

Problem solved.

Until we implement https://github.com/encode/uvicorn/issues/1453, there's no way we can do this properly.
