### ISSUE TITLE
Error with websockets - wsproto.utilities.LocalProtocolError: Event CloseConnection(code=1000, reason='') cannot be sent in state ConnectionState.CLOSED

### ISSUE THREAD

**Issue by cibere** [Kludex/uvicorn#1769]
Error: 
```py
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\websockets\wsproto_impl.py", line 219, in run_asgi
    result = await self.app(self.scope, self.receive, self.send)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\middleware\proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 79, in __call__
    raise exc
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 341, in handle
    await self.app(scope, receive, send)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 82, in app
    await func(session)
  File "C:\Users\name\OneDrive\Desktop\websocket_test\server.py", line 29, in websocket_endpoint
    await websocket.close()
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\websockets.py", line 180, in close
    await self.send(
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\websockets.py", line 85, in send
    await self._send(message)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 65, in sender
    await send(message)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\protocols\websockets\wsproto_impl.py", line 299, in send
    output = self.conn.send(
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\wsproto\__init__.py", line 64, in send
    data += self.connection.send(event)
  File "C:\Users\name\AppData\Local\Programs\Python\Python310\lib\site-packages\wsproto\connection.py", line 107, in send
    raise LocalProtocolError(
wsproto.utilities.LocalProtocolError: Event CloseConnection(code=1000, reason='') cannot be sent in state ConnectionState.CLOSED.
```

Code:
```py
from starlette.applications import Starlette
from starlette.websockets import WebSocket, WebSocketDisconnect

app = Starlette()

@app.websocket_route("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    while True:
        try:
            mesg = await websocket.receive_text()
        except WebSocketDisconnect:
            break

        if "u" in mesg:
            await websocket.send_json({"action": "x", "link": "..."})
        else:
            await websocket.send_json({"message": "no new actions"})

    await websocket.close()


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app)
```
Error occurs when the client disconnects from the websocket

**Comment by iudeen** [comment]
I confirmed, this is reproducible in both 19.0 and from master branch. 

On Debug, found this:
![image](https://user-images.githubusercontent.com/10519440/202886032-1c9d4995-41fc-45d0-aa85-65dc74f2d5d8.png)

The `CloseConnection` is sent by this line
https://github.com/encode/uvicorn/blob/53d7d1ed78c89f3a41937b3992c4a51ce9042021/uvicorn/protocols/websockets/wsproto_impl.py#L103-L104

before 
https://github.com/encode/uvicorn/blob/53d7d1ed78c89f3a41937b3992c4a51ce9042021/uvicorn/protocols/websockets/wsproto_impl.py#L281-L291

**Comment by iudeen** [comment]
One possible suggestion to resolve (I am not sure yet), is to remove the logic to close connection in `handle_close`.

```python
    def handle_close(self, event):
        # if self.conn.state == ConnectionState.REMOTE_CLOSING:
        #     self.transport.write(self.conn.send(event.response()))
        self.queue.put_nowait({"type": "websocket.disconnect", "code": event.code})
        # self.transport.close()
```

**Comment by Kludex** [comment]
This is not a bug. I agree the error message is not very clear, and we can think about changing it.

The problem here is that you are ignoring the `WebSocketDisconnect` exception, and trying to close the connection anyway.

There are two ways to solve this issue:

1. Use `WebSocketState`.
```diff
from starlette.applications import Starlette
- from starlette.websockets import WebSocket, WebSocketDisconnect
+ from starlette.websockets import WebSocket, WebSocketDisconnect, WebSocketState

app = Starlette()


@app.websocket_route("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    while True:
        try:
            mesg = await websocket.receive_text()
        except WebSocketDisconnect:
            break

        if "u" in mesg:
            await websocket.send_json({"action": "x", "link": "..."})
        else:
            await websocket.send_json({"message": "no new actions"})

+    if not WebSocketState.DISCONNECTED:
+        await websocket.close()
-     await websocket.close()


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app)
```
2. Stop execution on `WebSocketDisconnect`
```diff
from starlette.applications import Starlette
from starlette.websockets import WebSocket, WebSocketDisconnect

app = Starlette()


@app.websocket_route("/ws")
async def websocket_endpoint(websocket: WebSocket):
    await websocket.accept()
    while True:
        try:
            mesg = await websocket.receive_text()
        except WebSocketDisconnect:
-             break
+             return

        if "u" in mesg:
            await websocket.send_json({"action": "x", "link": "..."})
        else:
            await websocket.send_json({"message": "no new actions"})


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app)
```

I think this last method is more clear. :man_shrugging: 

In any case, we can try to raise a `RuntimeError` or something, but there's no bug here.

**Comment by iudeen** [comment]
Aah, I didn't notice websockets.close() in OP's code 😞
