### ISSUE TITLE
No module named `wsproto`

### ISSUE THREAD

**Issue by thomasjiangcy** [Kludex/uvicorn#178]
It's used in `wsproto_impl.py` but is not specified as a requirement in `setup.py`. When I run it with gunicorn:

```
gunicorn config.asgi:application \
        -w ${GUNICORN_WORKERS} \
        -k uvicorn.workers.UvicornWorker \
        -b 0.0.0.0:8000 \
        --reload
```

It'll throw:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 135, in load_class
    mod = import_module('.'.join(components))
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  ...
  File "/usr/local/lib/python3.6/site-packages/uvicorn/workers.py", line 13, in <module>
    from uvicorn.protocols.websockets.wsproto_impl import WSProtocol
  File "/usr/local/lib/python3.6/site-packages/uvicorn/protocols/websockets/wsproto_impl.py", line 6, in <module>
    import wsproto.connection
  ModuleNotFoundError: No module named 'wsproto'
```

Should probably add the requirement to `setup.py`?

**Comment by lovelydinosaur** [comment]
That shouldn't have been set to the default on gunicorn, as it's an *optional* alternate websocket implementation, rather than the default.

I've fixed it up in 0.3.2 - the default is now `websockets` again, which *is* in the setup.py.

Install 0.3.2 and give that a try.

Thanks for the report!
