### ISSUE TITLE
Logging errors when running paperless-ngx with uvicorn 0.20.0

### ISSUE THREAD

**Issue by eomanis** [Kludex/uvicorn#1806]
### Discussed in https://github.com/encode/uvicorn/discussions/1796

<div type='discussions-op-text'>

<sup>Originally posted by **eomanis** December  4, 2022</sup>
Basically, when using uvicorn to run [paperless-ngx](https://github.com/paperless-ngx/paperless-ngx), the application server produces many "[logging errors](https://github.com/paperless-ngx/paperless-ngx/issues/1280)" accompanied by stack traces.

The error message is:

```
TypeError: cannot unpack non-iterable NoneType object
```

The logging errors can be silenced by disabling access logs with `--no-access-log`.

Apart from that the application runs as expected; it mainly is a nuisance that forces the user to switch off access logging lest the log gets flooded.

Before I file an issue for uvicorn I would like to rule out that paperless-ngx is misbehaving.

The current version of paperless-ngx, 1.10.1, pulls uvicorn 0.19.0 in its requirements.txt.
This issue is present with both uvicorn 0.19.0 and 0.20.0.

Example:
```
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 681, in format
    s = self.formatMessage(record)
  File "/srv/paperless/python-venv/lib/python3.10/site-packages/uvicorn/logging.py", line 104, in formatMessage
    (
TypeError: cannot unpack non-iterable NoneType object
Call stack:
  File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/srv/paperless/python-venv/lib/python3.10/site-packages/concurrent_log_handler/queue.py", line 49, in _monitor
    super()._monitor()
Message: 'XXX.XXX.XXX.XXX:XXXXX - "GET /accounts/login/?next=/ HTTP/1.0" 200'
Arguments: None
```

Any feedback is appreciated.</div>

**Comment by Kludex** [comment]
Let's continue on the discussion (https://github.com/encode/uvicorn/discussions/1796).
