### ISSUE TITLE
TypeError: An asyncio.Future, a coroutine or an awaitable is required

### ISSUE THREAD

**Issue by felipe3dfx** [Kludex/uvicorn#185]
Hi

I was trying to run uvicorn + Django channels but i get this error:
```
2018-08-29 07:35:43 -0500] [9160] [ERROR] Exception in ASGI application
Aug 29 07:35:43 sofia gunicorn[9118]: Traceback (most recent call last):
Aug 29 07:35:43 sofia gunicorn[9118]:   File "/usr/local/lib/python3.6/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 140, in run_asgi
Aug 29 07:35:43 sofia gunicorn[9118]:     result = await asgi(self.asgi_receive, self.asgi_send)
Aug 29 07:35:43 sofia gunicorn[9118]:   File "/usr/local/lib/python3.6/dist-packages/channels/sessions.py", line 175, in __call__
Aug 29 07:35:43 sofia gunicorn[9118]:     return await self.inner(receive, self.send)
Aug 29 07:35:43 sofia gunicorn[9118]:   File "/usr/local/lib/python3.6/dist-packages/channels/middleware.py", line 41, in coroutine_call
Aug 29 07:35:43 sofia gunicorn[9118]:     await inner_instance(receive, send)
Aug 29 07:35:43 sofia gunicorn[9118]:   File "/usr/local/lib/python3.6/dist-packages/channels/consumer.py", line 54, in __call__
Aug 29 07:35:43 sofia gunicorn[9118]:     await await_many_dispatch([receive, self.channel_receive], self.dispatch)
Aug 29 07:35:43 sofia gunicorn[9118]:   File "/usr/local/lib/python3.6/dist-packages/channels/utils.py", line 57, in await_many_dispatch
Aug 29 07:35:43 sofia gunicorn[9118]:     await task
Aug 29 07:35:43 sofia gunicorn[9118]:   File "/usr/local/lib/python3.6/dist-packages/channels/utils.py", line 49, in await_many_dispatch
Aug 29 07:35:43 sofia gunicorn[9118]:     result = task.result()
Aug 29 07:35:43 sofia gunicorn[9118]:   File "/usr/local/lib/python3.6/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 223, in asgi_receive
Aug 29 07:35:43 sofia gunicorn[9118]:     data = await self.recv()
Aug 29 07:35:43 sofia gunicorn[9118]:   File "/usr/local/lib/python3.6/dist-packages/websockets/protocol.py", line 336, in recv
Aug 29 07:35:43 sofia gunicorn[9118]:     loop=self.loop, return_when=asyncio.FIRST_COMPLETED)
Aug 29 07:35:43 sofia gunicorn[9118]:   File "/usr/lib/python3.6/asyncio/tasks.py", line 311, in wait
Aug 29 07:35:43 sofia gunicorn[9118]:     fs = {ensure_future(f, loop=loop) for f in set(fs)}
Aug 29 07:35:43 sofia gunicorn[9118]:   File "/usr/lib/python3.6/asyncio/tasks.py", line 311, in <setcomp>
Aug 29 07:35:43 sofia gunicorn[9118]:     fs = {ensure_future(f, loop=loop) for f in set(fs)}
Aug 29 07:35:43 sofia gunicorn[9118]:   File "/usr/lib/python3.6/asyncio/tasks.py", line 526, in ensure_future
Aug 29 07:35:43 sofia gunicorn[9118]:     raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
Aug 29 07:35:43 sofia gunicorn[9118]: TypeError: An asyncio.Future, a coroutine or an awaitable is required
```
django==2.0.7
channels==2.1.3
gunicorn==19.9.0
uvicorn==0.3.2

Any ideas?

**Comment by lovelydinosaur** [comment]
Can you show the command line you're using to run the app?

Does the equivalent work if you swap it out for daphne without changing anything else?

**Comment by felipe3dfx** [comment]
Hi, when i had daphne the error didn't show up

gunicorn service is:

```
/etc/systemd/system/gunicorn.service

[Unit]
Description=gunicorn daemon
Requires=gunicorn.socket
After=network.target

[Service]
PIDFile=/run/gunicorn/pid
User=deploy
Group=deploy
RuntimeDirectory=gunicorn
WorkingDirectory=/home/deploy/XXXXX/
ExecStart=/usr/local/bin/gunicorn app.asgi:application --worker-class uvicorn.workers.UvicornWorker --pid /run/gunicorn/pid --bind unix:/run/gunicorn/socket --preload --workers 4
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```

**Comment by lovelydinosaur** [comment]
Are you able to run it directly with `uvicorn` from the command line, rather than via gunicorn with the uvicorn worker class? That'd help us narrow down some things. If you can then you could try using `--ws wsproto` and see if you get different behavior there or not.

**Comment by lovelydinosaur** [comment]
Going to close this one of, given that I don't have anything easily reproducible here.
We've got some far better debug-level logging now.

Running with uvicorn from the command line would really help narrow any issues down too.

**Comment by Teippo2020** [comment]
Getting same error, running it with uvicorn, 

```
INFO: Started server process [28]
INFO: Waiting for application startup.
INFO: Started server process [32]
INFO: ASGI 'lifespan' protocol appears unsupported.
INFO: Started server process [31]
INFO: Started server process [27]
INFO: Started server process [29]
INFO: Waiting for application startup.
INFO: Waiting for application startup.
INFO: Waiting for application startup.
INFO: ASGI 'lifespan' protocol appears unsupported.
INFO: Started server process [33]
INFO: ASGI 'lifespan' protocol appears unsupported.
INFO: ASGI 'lifespan' protocol appears unsupported.
INFO: Waiting for application startup.
INFO: ASGI 'lifespan' protocol appears unsupported.
INFO: Started server process [34]
INFO: Waiting for application startup.
INFO: ASGI 'lifespan' protocol appears unsupported.
INFO: Started server process [30]
INFO: Waiting for application startup.
INFO: Waiting for application startup.
INFO: ASGI 'lifespan' protocol appears unsupported.
INFO: ASGI 'lifespan' protocol appears unsupported.
INFO: Started server process [35]
INFO: Waiting for application startup.
INFO: ASGI 'lifespan' protocol appears unsupported.
INFO: ('127.0.0.1', 42278) - "WebSocket /ws/notifications/" 403
187.202.134.228 - - [17/May/2019:17:39:15 +0000] "GET /ws/notifications/?token=ee58a81f3829471c49996d9eed087e044d773fefb56762280247882e5597f207-1558113145-1558109749 HTTP/1.1" 403 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.131 Safari/537.36"
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 146, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__
    await instance(receive, send)
  File "/usr/local/lib/python3.7/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/usr/local/lib/python3.7/site-packages/channels/utils.py", line 59, in await_many_dispatch
    await task
  File "/usr/local/lib/python3.7/site-packages/channels/utils.py", line 51, in await_many_dispatch
    result = task.result()
  File "/usr/local/lib/python3.7/site-packages/newrelic/api/transaction_context.py", line 63, in send
    return self.__wrapped__.send(value)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 226, in asgi_receive
    data = await self.recv()
  File "/usr/local/lib/python3.7/site-packages/websockets/protocol.py", line 419, in recv
    return_when=asyncio.FIRST_COMPLETED,
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 357, in wait
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 357, in <setcomp>
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/usr/local/lib/python3.7/site-packages/newrelic/hooks/coroutines_asyncio.py", line 20, in _wrap_ensure_future
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 588, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
2019/05/17 17:39:16 [info] 12#12: *3 client 187.202.134.228 closed keepalive connection
```

Here is the command used to start uvicorn:

` uvicorn --host 0.0.0.0 --port 9000  --log-level info --workers 9 api.asgi:application`

**Comment by Teippo2020** [comment]
The bus is fixed installing `wsproto` and using it with the command `--ws wsproto`

**Comment by jamneck** [comment]
> The bus is fixed installing `wsproto` and using it with the command `--ws wsproto`

How did you set `--ws wsproto` for gunicorn?

**Comment by victorct** [comment]
> > The bus is fixed installing `wsproto` and using it with the command `--ws wsproto`
> 
> How did you set `--ws wsproto` for gunicorn?

I did it with uvicorn not with gunicorn :/

**Comment by Christophe31** [comment]
You can pass uvicorn arg to gunicorn by making your own worker like this:
```python
from uvicorn.workers import UvicornWorker

class DjangoUvicornWorker(UvicornWorker):
    CONFIG_KWARGS = {
        "loop": "uvloop",
        "http": "httptools",
        "lifespan": "off",  # lifespan is not handled by django channels for now
        "ws": "wsproto",
    }
```
Then use this as your --worker-class

**Comment by kingraphaii** [comment]
@Christophe31 your snippet saved me hours. Thanks much. Anyone who stumbles upon this, you'll also need to `pip install wsproto` since it doesn't come with the default Uvicorn installation.
