### ISSUE TITLE
Ctrl+C in terminal broken on windows

### ISSUE THREAD

**Issue by davidefortunatotecnos** [Kludex/uvicorn#1972]
With last release of Uvicorn 0.22.0 doing CTRL+C in a windows terminal doesn't work anymore. 
Everything is frozen and it is impossible to stop it. In addition the command --reload is broken too, because it doesn't restart anymore, probably because of the same issue.

Tried on Windows 11 and Powershell 7.3.4.

Downgrading to version 0.21.1 makes it works again.

**Comment by lzcmian** [comment]
same question

**Comment by urfswe** [comment]
when you launch without testing properly that will happen, also same here, in addition to that issue with "--reload" parameter over time it stucks and doesn't update api endpoints

**Comment by AshminJayson** [comment]
Also the issue of the everything being frozen is generally triggered right after watchfiles tries restarting the server/detected a change, also killing the process manually using the port number doesn't fully terminate it and does not allow for the port to be reused without a full system reboot.

**Comment by JinglingB** [comment]
Crude monkey-patching hack to use `SetConsoleCtrlHandler`, which actually has its handlers called unlike `signal.signal`'s. Don't add this to anything serious:

```py
import sys

if __name__ == "__main__":
    if sys.platform == "win32":
        # Based on Eryk Sun's code: https://stackoverflow.com/a/43095532
        import ctypes

        from signal import SIGINT, CTRL_C_EVENT

        _console_ctrl_handlers = {} # must be global / kept alive to avoid GC

        kernel32 = ctypes.WinDLL("kernel32", use_last_error=True)

        PHANDLER_ROUTINE = ctypes.WINFUNCTYPE(
            ctypes.wintypes.BOOL,
            ctypes.wintypes.DWORD)

        def _errcheck_bool(result, func, args):
            if not result:
                raise ctypes.WinError(ctypes.get_last_error())
            return args

        kernel32.SetConsoleCtrlHandler.errcheck = _errcheck_bool
        kernel32.SetConsoleCtrlHandler.argtypes = (
            PHANDLER_ROUTINE,
            ctypes.wintypes.BOOL)

        from uvicorn.supervisors.multiprocess import Multiprocess
        uvicorn_multiprocess_startup_orig = Multiprocess.startup
        def uvicorn_multiprocess_startup(self, *args, **kwargs):
            ret = uvicorn_multiprocess_startup_orig(self, *args, **kwargs)

            def win_ctrl_handler(dwCtrlType):
                if (dwCtrlType == CTRL_C_EVENT and
                    not self.should_exit.is_set()):
                    kernel32.SetConsoleCtrlHandler(_console_ctrl_handlers[win_ctrl_handler], False)
                    self.signal_handler(SIGINT, None)
                    del _console_ctrl_handlers[win_ctrl_handler]
                    return True
                return False

            if win_ctrl_handler not in _console_ctrl_handlers:
                h = PHANDLER_ROUTINE(win_ctrl_handler)
                kernel32.SetConsoleCtrlHandler(h, True)
                _console_ctrl_handlers[win_ctrl_handler] = h

            return ret
        Multiprocess.startup = uvicorn_multiprocess_startup

    uvicorn.run("app", workers=4)
```

**Comment by AshminJayson** [comment]
> Also the issue of the everything being frozen is generally triggered right after watchfiles tries restarting the server/detected a change, also killing the process manually using the port number doesn't fully terminate it and does not allow for the port to be reused without a full system reboot.

The current workaround which works for this is to run `uvicorn` from the `main` function of the app rather than having to run it directly as a command line command. 

_This ensures that the port is freed and also terminates the program correctly._

```python

if __name__ == '__main__':
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)

```

**Comment by olafrv** [comment]
Does not works for me @AshminJayson .
I switched to [hypercorn](https://github.com/pgjones/hypercorn) in the meantime.

```
if __name__ == '__main__':
    # https://github.com/encode/uvicorn/issues/1972
    asyncio.run(serve(app, Config()))
```

Sample:

```
PS C:\Users\olafr\test> python .\server.py
[2023-10-28 02:19:19 +0200] [13228] [INFO] Running on http://127.0.0.1:8000 (CTRL + C to quit)
2023-10-28 02:19:19,472 loglevel=INFO   logger=hypercorn.error info() L106  Running on http://127.0.0.1:8000 (CTRL + C to quit)
PS C:\Users\olafr\test>
```

**Comment by humrochagf** [comment]
@olafrv can you check if the changes that are in this MR works on your side?

https://github.com/encode/uvicorn/pull/2059

**Comment by olafrv** [comment]
@humrochagf , tested, nothing changes, but thanks to your PR I nailed down the problem.

I'm on latests Windows 11 23H2 builtin Poweshell, VSCode 1.83.1, Python 3.12.0 (tags/v3.12.0:0fb18b0).

The signal is indeed received (CTRL+C), since the shutdown starts, both in 0.23.2 and your https://github.com/encode/uvicorn/pull/2059 .

However, the shutdown process hangs forever, giving the impression of not working, you only see:
`INFO:     Shutting down`

It does not matter if you pass or not the `--reload` and/or `--reload-delay`, so you end up doing:
`taskkill /f /im "uvicorn.exe"`

I found that the [server.wait_closed()](https://github.com/encode/uvicorn/blob/732cef6ff7700e7c50e6123276f881d483897f43/uvicorn/server.py#L272) never returns (or timeouts after minutes):

I guess the [socket.close()](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.Server.close) is never closed until timeout?:
https://github.com/encode/uvicorn/blob/732cef6ff7700e7c50e6123276f881d483897f43/uvicorn/server.py#L270

My dirty workaround:
```
      for server in self.servers:
            # await server.wait_closed()
            pass
```

I also saw Python has an open [asyncio.Server.wait_closed() appears to hang indefinitely in 3.12.0a7](https://github.com/python/cpython/issues/104344) but I didn't check how it is related to the `server.py` logic in depth.

So you can merge https://github.com/encode/uvicorn/pull/2059 but won't solve the(my) problem.

It is reproducible even with this `helloworld.py` but it gets more evident on more complex apps:

```python
from fastapi import FastAPI

app = FastAPI()

@app.get("/")
async def read_root():
    return {"Hello": "World"}
```

**Comment by humrochagf** [comment]
Alright, thanks for taking a look at it, I'll run some tests in python 3.12 to see if I can reproduce it 🙂

**Comment by jcheng5** [comment]
There's a discussion on this issue here, along with a proposed fix: https://github.com/encode/uvicorn/discussions/2122

**Comment by tonnydourado** [comment]
By the way, I'm having the same problem for a while, on Windows 10, both Python 3.9 and 3.11. Don't remember the version I was using with 3.9, but with 3.11 is 0.24.0.post1.

Downgrading to 0.21.1 seems to improve the reload behavior, but CTRL+C still doesn't work, with or without reload. 

By the way, this is somewhat intermittent. It's broken *most* of the time, but sometimes it just works normally, just often enough to make me doubt my sanity, competence, and the nature of reality itself.

**Comment by frankhuurman** [comment]
Not entirely sure if this is the same issue but on Windows 10 I'm also having issues since a python 3.12 upgrade with the NiceGUI framework(that uses uvicorn under the hood for filewatching/serving).

Any time I edit & save a file while uvicorn is running, it seems to shut down some process and not properly pick up on file changes plus it's impossible to Ctrl+C out of the application unless I close the browser tab.

https://github.com/zauberzeug/nicegui/issues/2138

Python 3.11.x works fine, Python 3.12+ seems to break the filewatcher(unsure if the actual bug is in Uvicorn or in the asyncio/python 3.12/Windows combo).
On Mac OS/Linux it works fine with Py 3.12, it's just Windows that's seemingly picky.

**Comment by Mason-Chou** [comment]
I've been using this project for on Windows for quite a while and finally decided to spend some time tonight to look into why this annoying issue is happening. 

There has been some great discussions over possible fixes to this issue, but it seems like it comes down to the parent process, `supervisors.multiprocess.Multiprocess`, being unable to receive any signals from pressing Ctrl+C. 

Why is it the case? The Server subprocesses is able to receive the signals fine. Seems to be an [open bug](https://bugs.python.org/issue35935) with CPython `threading.Event.wait()` on Windows.

@humrochagf seems to be on the right path with #2059 by changing the behavior to use a timeout to unblock the parent process and have it receive all the handled signals. Seems to be buggy still though.

The fix I've done was replacing the `self.should_exit.wait()` with a simple `time.sleep()` loop in `supervisors.multiprocess.Multiprocess`
```python
    def run(self) -> None:
        self.startup()
        while not self.should_exit.is_set():
            time.sleep(.1)
        self.shutdown()
```

Seems to work with my build:
- Windows 11 
- Python 3.12
- uvicorn master branch

 I'm sure it'll work for older versions. `--reload` works for me but still has some annoying CancelledError.

**Comment by humrochagf** [comment]
Hello, now that we have #2183 landing on version 0.30.0 the new process manager seems to solve this issue.

If anyone that was also facing this issue is able to check with this version I guess we are good to close this one 🙂

**Comment by spikecodes** [comment]
Same issue still happening for me on v0.30.1

**Comment by davidefortunatotecnos** [comment]
Hello, I just tried with version 0.30.1 and i confirm that the issue is still happening, it is not fixed

**Comment by maxfischer2781** [comment]
Is this dependent on the OS version or shell/terminal used, perhaps? That would explain why it works for some people but not for others.

**Comment by davidefortunatotecnos** [comment]
@maxfischer2781 i provide some additional information about OS and shell, that are changed a bit since the first post i made due to some Windows updates, but are pretty similar. 

Today i tried with these versions:
OS: Windows 11 23H2 Build 22631.3672
Powershell 7.4.2

If i downgrade to Uvicorn version 0.21.1 everything works fine, but every version i tried after the 0.21.1 always had the issue

**Comment by Danipulok** [comment]
Encountered the same issue on Win10 with uvicorn `0.27.0.post1`.
When I then tested it with `0.21.2`, `0.22.2` and `0.27.0.post1` again, everything worked okay (tested simple code changes).

It seems this bug is pretty rare and maybe happens only if something specific in code changes? Or even env files, can't be sure.

My command:
```Makefile
ENV_FILE := $(PWD)/.local.env
.PHONY: main
main:
    uvicorn project.app:create_app --factory --reload --port=8100 --env-file=$(ENV_FILE)
```

PS: using `PyCharm 2024.1.2` if important. Also enabled feature `new terminal`. But since this issues doesn't always happen, I doubt it's related to PyCharm (at least).

**Comment by Nochnikov** [comment]
The same problem with uvicorn 0.30.1 on Win10. 

The frequency of the is alarming. I just reopened IDE and everything work fine.

**Comment by SomaLily** [comment]
My Linux get a similar problem , when Crtl+C in the envirenment with py:12.4 and uvi:0.30.1, it raise a "KeyboardInterrupt()" ; but when I back to the env with py:12.0 and uvi:0.23.2 ,  the Ctrl+C shutdown gracefully without any raise.

**Comment by YuriFontella** [comment]
this still happens with version 0.30.1 with windows 11 powershell 7.4.3

poetry shell
uvicorn main:app --reload

when a file is modified everything freezes in this part:
WARNING: WatchFiles detected changes in 'main.py'. Reloading...

ctrl + c does not work
you need to kill all python processes

**Comment by Abeautifulsnow** [comment]
uvicorn0.30.1 also has this problem. The Windows terminal consistently experiences issues, freezing whether you attempt to stop it with Ctrl+C or there's a file change. So, I switched to wsl and everything is fine now.

**Comment by kk7188048** [comment]
So there is no way for stopping Uvicorn if its reloaded?

**Comment by Kludex** [comment]
If someone with windows gives me a step by step on how to install Python and reproduce this on a windows 11 machine, I can debug it. 👍

Preferably with an editor that I can modify uvicorn internals.

**Comment by tugofpeas** [comment]
It's not limited to windows 11, windows 10 is affected as well. To replicate, just run with the --reload option. It may work correctly a few times - in my case I can 'CTRL + C' after the first run; any subsequent runs or simply after awhile it will not respond to 'CTRL + C'. To exit you have to have a second terminal open to kill python processes, in order to kill the uvicorn process.

**Comment by prochor666** [comment]
Use hypercorn, especially with fastapi. Uvicorn does not supprt all the features and is very unstable.

**Comment by Edfrost321** [comment]
Very frustrating and it seems like this has been an issue for some time. Is there any update on attempts to fix this?
The --reload is a fantastic feature, but as it stands windows development is even longer than non --reload as I have to kill the python process after every file save and restart.

**Comment by Kludex** [comment]
Well @Edfrost321... Let me explain it.

It seems this issue is not reproducible in every Windows machine. You can just read this issue to notice that. I'm actually writing this comment from a Windows machine that can't reproduce it.

On the other hand, the ones that can reproduce the issue are only complaining and expecting the maintainer to solve this.
And... I'm the only maintainer. I can't reproduce it. How do you expect me to solve it?

Anyone really interested, should open a pull request, or... I'm also open to give my address for people interested in sending me a Windows machine with this issue as well. Maybe you can ask Microsoft or JetBrains (https://github.com/encode/uvicorn/issues/2000).

**Comment by YuriFontella** [comment]
On my Windows system there are two programs, "Terminal" which I define as the main profile, Powershell, and "Powershell" itself.

"Terminal" has much more interesting settings than using "Powershell" directly, but in my case it has this problem of not reloading.

I still think it could be a graphical problem, when I click on it and give it focus, the reloading continues.

![image](https://github.com/user-attachments/assets/68708440-c57e-4117-a25e-ad48618e0952)

If I do more than one update, it generates this error.

![image](https://github.com/user-attachments/assets/22efeae4-567a-4c62-92ef-f809779782c1)

```
ERROR:    Traceback (most recent call last):
  File "C:\Users\yurif\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yurif\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yurif\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\yurif\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 123, in run
    raise KeyboardInterrupt()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\yurif\AppData\Local\pypoetry\Cache\virtualenvs\auth-1Lj04NOI-py3.12\Lib\site-packages\litestar\_asgi\asgi_router.py", line 181, in lifespan
    await receive()
  File "C:\Users\yurif\AppData\Local\pypoetry\Cache\virtualenvs\auth-1Lj04NOI-py3.12\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yurif\AppData\Local\Programs\Python\Python312\Lib\asyncio\queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError
````

and the ctrl+c problem still happens
uvicorn 0.30.6
python 3.12.5

**Comment by johnlowe-123** [comment]
Have discovered something that might be helpful here. I was having exactly this issue, very consistently. The failure to reload, the locking up of the console etc...

The issue is completely resolved when I disable default logging:

`uvicorn app:app --reload --log-level critical`

If I leave logging on, issue returns. If I turn it off, issue goes away. Hope that is helpful in tracking down the bug.

**Comment by lingy-Mg** [comment]
I'm having the same glitch as well

**Comment by YuriFontella** [comment]
I have this same problem using vscode and poetry, I temporarily solved my problem by using watchfiles directly and everything worked perfectly

```
watchfiles "uvicorn app:app --port 7000" .
```

windows 11
python 3.12.7
powershell 7.4.5
uvicorn 0.31.1

**Comment by Danipulok** [comment]
@YuriFontella thank you so much!
Seems to work like a charm
And kinda seems to me that it's faster then using `uvicorn`'s --reload
But maybe that's just placebo

Anyway, have been using for an hour and everything work perfect

**Comment by YuriFontella** [comment]
@Danipulok I advise everyone to use the watchfiles filter, I use pycharm and it has a strategy of backing up files when saving, which ends up causing unnecessary reloads

```
watchfiles --filter python "uvicorn app:app --port 7000" .
```

and I also had infinite reloads using the Litestar file-based stores module, I only solved it with the filter

**Comment by Danipulok** [comment]
That's really nice
Thanks a lot again, @YuriFontella!

**Comment by Allaoua9** [comment]
In my case, the issue was caused when i tried to disable the uvicorn error logger inside the lifespan event 😕 .

```python
@asynccontextmanager
async def lifespan(app: FastAPI) -> AsyncIterator[None]:
    # Disable default uvicorn error logs. Error logging is handled by the app.
    error_logger = logging.getLogger("uvicorn.error")
    error_logger.disabled = True

    yield
```
I have no explanation though.

When starting the app i get the log :

`INFO:     Waiting for application startup.`

And i never get the log : 

`INFO:     Application startup complete.`

**Comment by chris-avens** [comment]
> I have this same problem using vscode and poetry, I temporarily solved my problem by using watchfiles directly and everything worked perfectly
> 
> ```
> watchfiles --filter python "uvicorn app:app --port 7000" .
> ```
> 
> windows 11 python 3.12.7 powershell 7.4.5 uvicorn 0.31.1

where exactly should i put this script? tried running it on a different terminal (because the terminal where i ran uvicorn does not respond to anything). it did not work

**Comment by mathenymi** [comment]
This issue is not limited to windows. Seeing this on MacOS-14.4.1 as well. Python3.12.7. Ctrl-C does not stop the server and it either just hangs forever or wont stop background tasks.

**Comment by Kludex** [comment]
> This issue is not limited to windows. Seeing this on MacOS-14.4.1 as well. Python3.12.7. Ctrl-C does not stop the server and it either just hangs forever or wont stop background tasks.

It's not the same issue.

**Comment by vinhkhangphung** [comment]
Give thanks to @YuriFontella. Goated solution tbh.

**Comment by netvoip** [comment]
I have the same issue. 
Windows 11, Windows Terminal + PowerShell, Python 3.11, uvicorn 0.32.1.
Ctlr-C stops working not immediately but after some time (or after some starts and stops). It seems like python process at some time starts to live on its own because even if I kill the whole Windows Terminal, python with uvicorn stays in processes.
Neither watchfiles nor `__name__ == '__main__'` check helped. Reload works well in the meantime.

**Comment by Kludex** [comment]
Can people test this branch: https://github.com/encode/uvicorn/pull/2532/ to see if it solves the issue?

**Comment by ZhimaoLin** [comment]
> On my Windows system there are two programs, "Terminal" which I define as the main profile, Powershell, and "Powershell" itself.
> 
> "Terminal" has much more interesting settings than using "Powershell" directly, but in my case it has this problem of not reloading.
> 
> I still think it could be a graphical problem, when I click on it and give it focus, the reloading continues.
> 
> ![image](https://private-user-images.githubusercontent.com/4920619/359641014-68708440-c57e-4117-a25e-ad48618e0952.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MTMzNTIsIm5iZiI6MTczNDkxMzA1MiwicGF0aCI6Ii80OTIwNjE5LzM1OTY0MTAxNC02ODcwODQ0MC1jNTdlLTQxMTctYTI1ZS1hZDQ4NjE4ZTA5NTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMDAxNzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTBhZmI5MDU4YjYxYThhODJlYjc5OWIyNGNmODNjMjRjMjEyOTJkYWZlNjI4MjRkYzYxNTcwNmY3ODc0M2M5OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.f9hdbqS2GAkoX6b6qyqVIELAEAN-UwAKo0Qezgt0J_c)
> 
> If I do more than one update, it generates this error.
> 
> ![image](https://private-user-images.githubusercontent.com/4920619/359641451-22efeae4-567a-4c62-92ef-f809779782c1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ5MTMzNTIsIm5iZiI6MTczNDkxMzA1MiwicGF0aCI6Ii80OTIwNjE5LzM1OTY0MTQ1MS0yMmVmZWFlNC01NjdhLTRjNjItOTJlZi1mODA5Nzc5NzgyYzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMjNUMDAxNzMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGYwYzg0OTViZmUxYzZmMDQ2ZTk3N2Y2ZTlhMmFhZGQ0NDdlNjMwM2EyMmJmMzY5ODBkMGMyY2EzMWJkYTY0NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.aGihBp8uAmbNHDElt_M72_demBFIujzQZK77Lvu9Qq0)
> 
> ```
> ERROR:    Traceback (most recent call last):
>   File "C:\Users\yurif\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
>     return self._loop.run_until_complete(task)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\yurif\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
>     return future.result()
>            ^^^^^^^^^^^^^^^
> asyncio.exceptions.CancelledError
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\yurif\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
>     return runner.run(main)
>            ^^^^^^^^^^^^^^^^
>   File "C:\Users\yurif\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 123, in run
>     raise KeyboardInterrupt()
> KeyboardInterrupt
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\yurif\AppData\Local\pypoetry\Cache\virtualenvs\auth-1Lj04NOI-py3.12\Lib\site-packages\litestar\_asgi\asgi_router.py", line 181, in lifespan
>     await receive()
>   File "C:\Users\yurif\AppData\Local\pypoetry\Cache\virtualenvs\auth-1Lj04NOI-py3.12\Lib\site-packages\uvicorn\lifespan\on.py", line 137, in receive
>     return await self.receive_queue.get()
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\yurif\AppData\Local\Programs\Python\Python312\Lib\asyncio\queues.py", line 158, in get
>     await getter
> asyncio.exceptions.CancelledError
> ```
> 
> and the ctrl+c problem still happens uvicorn 0.30.6 python 3.12.5

This is the exact issue that I encountered. I solved it by downgrade uvicorn to `0.21.1`.

- Windows 11 Pro Version `24H2`
- Uvicorn `0.21.1`
- FastAPI `0.115.6`
- Pipenv `2024.4.0`

I guess they used different mechanism to detect file changes after `0.21.1`.

**Comment by IanMarcC** [comment]
I just ran into this issue while using FastAPI and NiceGUI. Using that branch seems to have fixed my issues with Ctrl + C.

**Comment by stephendrew** [comment]
> I have this same problem using vscode and poetry, I temporarily solved my problem by using watchfiles directly and everything worked perfectly
> 
> ```
> watchfiles "uvicorn app:app --port 7000" .
> ```
> 
> windows 11 python 3.12.7 powershell 7.4.5 uvicorn 0.31.1

This workaround works for me, thank you @YuriFontella

**Comment by parched** [comment]
> Can people test this branch: [#2532](https://github.com/encode/uvicorn/pull/2532) to see if it solves the issue?

That solves it for us. It had been hanging while reloading when run from VS Code using the internalConsole.

**Comment by brupelo** [comment]
Hi everyone, just wondering — any idea when a new release including this patch might be published on pypi?

I can confirm that old official pypi version `0.34.0` still has this issue on Windows 10 with Python 3.11.x. Like others, I've been using `watchfiles` as a workaround, and so far it's been working well enough. For reference, here's what I'm doing:

`configure.cmd`:

```
doskey serve=watchfiles --filter python --target-type command "uvicorn my_fastapi_svc.main:create_app --factory --host 0.0.0.0 --port 8000" .
```

That said, this is obviously not ideal. Ideally, we should be able to rely on `uvicorn`'s built-in reloading and proper process termination — especially for local development.

The main problem is that reloading was always a bit flaky on Windows, and at some point it just stopped working entirely for me. It would leave orphaned Python processes running, requiring manual cleanup via `taskkill`, Process Explorer, etc., which really disrupted the development flow and led me to look into alternatives.

Smooth and reliable process termination — particularly around hot-reloading — feels like a critical piece for any cross-platform app server. Hope this can be addressed soon!

**Comment by evnchn** [comment]
Dear All

It appears that I have found the GitHub issue that has been bothering me for ages, and I have new information to share. 

Notably, for how the Ctrl+C seems to "it works for some people but not for others":

- Computer 1: Ryzen 7 5800H, Ctrl+C almost never works. 
- Computer 2: Intel Celeron N100, Ctrl+C almost always works. 


So, the difficulty in reproducing the issue may lie in the fact that, if your computer is slow enough, you won't be affected by it, and vice versa. 

For anyone who is still interested in reproducing the issue, one way or another: try a faster machine if you want the issue to occur, or throttle your machine slower if you want it not occur. 

Please also list your specs so that I can check if my hypothesis is true.

**Comment by brupelo** [comment]
> Can people test this branch: [#2532](https://github.com/encode/uvicorn/pull/2532) to see if it solves the issue?

Thanks for the work on this! I wanted to test it out to see if it was doing the
job, but I ran into some crashes while installing uvicorn:
https://github.com/astral-sh/uv/issues/12898.

I took a closer look—especially with Windows in mind, since you mentioned
testing was needed there. Here are a few notes and suspicions that might help
track down the Ctrl+C inconsistencies:

---

### 🐟 1. `CTRL_C_EVENT` requires subprocess to be in a new process group

You're using:

```python
os.kill(self.process.pid, signal.CTRL_C_EVENT)
```

On Windows, for this to work reliably, the subprocess must be created with the
flag `CREATE_NEW_PROCESS_GROUP`. Otherwise, the `CTRL_C_EVENT` will silently
fail to reach the child. Can you confirm if `get_subprocess()` sets this?

> 🔍 Might be worth explicitly passing `creationflags=subprocess.CREATE_NEW_PROCESS_GROUP` in `get_subprocess()` when spawning on Windows.

---

### 🐟 2. Use of `GetConsoleWindow()` to decide signal strategy

```python
if ctypes.windll.kernel32.GetConsoleWindow() != 0:
```

This check assumes the current process has a console window — but that doesn't
guarantee the child process is attached to the same console or can receive
control events.

This may behave differently across Windows Terminal, VSCode Terminal, Git Bash,
etc. In some cases, `CTRL_C_EVENT` may do nothing even though this condition
passes.

---

### 🐟 3. Potential signal loss during restart logic

```python
if sys.platform == "win32" and self.is_restarting:
    self.is_restarting = False
else:
    self.should_exit.set()
```

This logic could potentially suppress `SIGINT` if it arrives during a restart
window. If a user hits `Ctrl+C` while the process is restarting, it might be
ignored or delayed unexpectedly.

> 🤔 Maybe worth logging when `is_restarting` suppresses a signal, to observe behavior more clearly during testing.

---

### 🐟 4. Signal handling and threading

You're using `threading.Event()` for shutdown signaling, which is generally
fine. But since Python only delivers signals to the **main thread**, any signal
handlers registered from a different thread might not behave as expected.

Depending on how `BaseReload` is run (especially when embedded in tools like
`watchfiles` or other wrappers), this might cause signals to be lost or not
caught properly.

---

### ✅ Why `watchfiles` works better?

As a side note — I’ve noticed that `watchfiles --run "uvicorn ..."` seems to
handle `Ctrl+C` perfectly on Windows. My guess is:

- It creates a proper subprocess group.
- It forwards signals explicitly.
- It avoids the `CTRL_C_EVENT` workaround altogether.

Might be worth comparing subprocess logic there if you're aiming for parity.

---

### 🔧 Suggestions

- Double-check `get_subprocess()` for process group handling.
- Consider `.send_signal(signal.CTRL_BREAK_EVENT)` as a more reliable fallback.
- Add more explicit logging around signal handling and subprocess restart to help testers confirm what's being triggered.

---

Anyway, first things first—I’d like to test your branch before any
feedback. As I mentioned, I wasn’t able to test it out yet.

I'll be testing it out on windows terminal eventually once i'm able to bootstrap the repo.

**Comment by ZiyuZ** [comment]
Just adding a data point in case it helps others.

On my setup (Windows), `Ctrl+C` did not work **at all** — not with `fastapi dev/run`, not with `uvicorn` (with or without `--reload`), and not even when running a plain `.py` file.

This only happened when using **WezTerm** as the terminal emulator.  
After switching to **Windows Terminal**, `Ctrl+C` worked normally in all cases.

If anyone is seeing similar behavior, it might be worth trying a different terminal to rule this out.

**Comment by ranganpeercore** [comment]
@echo off
echo Stopping all Python/uvicorn processes...
taskkill /F /IM python.exe /T >nul 2>&1
taskkill /F /IM uvicorn.exe /T >nul 2>&1
timeout /t 2 /nobreak >nul
echo Starting server on port "PORT NO"
python main.py

copy and paste this in a bat file and run the bat file
