### ISSUE TITLE
Django, uvicorn, gunicorn inside docker

### ISSUE THREAD

**Issue by developer992** [Kludex/uvicorn#2267]
### Initial Checks

- [X] I confirm this was discussed, and the maintainers suggest I open an issue.
- [X] I'm aware that if I created this issue without a discussion, it may be closed without a response.

### Discussion Link

```Text
...
```

### Description

```
 Traceback (most recent call last):
xxx|   File "/root/.cache/pypoetry/virtualenvs/xxx-admin-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
xxx|     result = await app(  # type: ignore[func-returns-value]
xxx|              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xxx|   File "/root/.cache/pypoetry/virtualenvs/xxx-admin-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
xxx|     return await self.app(scope, receive, send)
xxx|            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
xxx|   File "/root/.cache/pypoetry/virtualenvs/xxx-admin-9TtSrW0h-py3.11/lib/python3.11/site-packages/uvicorn/middleware/asgi2.py", line 16, in __call__
xxx|     instance = self.app(scope)
xxx|                ^^^^^^^^^^^^^^^
xxx| TypeError: WSGIHandler.__call__() missing 1 required positional argument: 'start_response'

```

I use poetry and this is how i run it:
```

CMD [\
    "poetry", \
    "run", \
    "gunicorn", \
    "xxx.wsgi:application", \
    "--workers", "2", \
     "--worker-class", "uvicorn.workers.UvicornWorker", \
    "--bind", "0.0.0.0:9000" \
]
```

What is going on, this should  work ... 

### Example Code

```Python
...
```

### Python, Uvicorn & OS Version

```Text
...
```

> [!IMPORTANT]
> - We're using [Polar.sh](https://polar.sh/encode) so you can upvote and help fund this issue.
> - We receive the funding once the issue is completed & confirmed by you.
> - Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/encode/uvicorn/issues/2267">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/encode/uvicorn/issues/2267/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/encode/uvicorn/issues/2267/pledge.svg">
</picture>
</a>

**Comment by developer992** [comment]
why is it even spinning up asgi when i am clearly using wsgi ?
`
    "xxx.wsgi:application", \`
