### ISSUE TITLE
Exception in ASGI application - 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by felipe3dfx** [Kludex/uvicorn#242]
Hello, I have 'NoneType' error on asgi_send method, im not sure for why this happens:

```
[2018-11-07 22:13:39 -0500] [2868] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 140, in run_asgi
    result = await asgi(self.asgi_receive, self.asgi_send)
  File "/usr/local/lib/python3.6/dist-packages/channels/sessions.py", line 175, in __call__
    return await self.inner(receive, self.send)
  File "/usr/local/lib/python3.6/dist-packages/channels/middleware.py", line 41, in coroutine_call
    await inner_instance(receive, send)
  File "/usr/local/lib/python3.6/dist-packages/channels/consumer.py", line 54, in __call__
    await await_many_dispatch([receive, self.channel_receive], self.dispatch)
  File "/usr/local/lib/python3.6/dist-packages/channels/utils.py", line 50, in await_many_dispatch
    await dispatch(result)
  File "/usr/local/lib/python3.6/dist-packages/channels/consumer.py", line 67, in dispatch
    await handler(message)
  File "/usr/local/lib/python3.6/dist-packages/channels/generic/websocket.py", line 173, in websocket_connect
    await self.connect()
  File "/home/deploy/xxxxxx/app/consumers.py", line 314, in connect
    await self.accept()
  File "/usr/local/lib/python3.6/dist-packages/channels/generic/websocket.py", line 186, in accept
    await super().send({"type": "websocket.accept", "subprotocol": subprotocol})
  File "/usr/local/lib/python3.6/dist-packages/channels/consumer.py", line 75, in send
    await self.base_send(message)
  File "/usr/local/lib/python3.6/dist-packages/channels/sessions.py", line 226, in send
    return await self.real_send(message)
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/protocols/websockets/websockets_impl.py", line 170, in asgi_send
    self.scope["server"][0],
TypeError: 'NoneType' object is not subscriptable
```
Any ideas?

Django==2.1.3
channels==2.1.5
channels_redis==2.3.1
gunicorn==19.9.0
uvicorn==0.3.20

**Comment by lovelydinosaur** [comment]
How easily can you reproduce the issue?

**Comment by matteing** [comment]
Same issue here.

**Comment by matteing** [comment]
On install, essentially. Just installed and it doesn't work. :(

**Comment by agronick** [comment]
This issue is very easy to produce and very easy to fix. Happens out of the box with latest version and prevents websockets from working. 

It comes from protocol/utils.py in this method
```
def get_local_addr(transport):
    info = transport.get_extra_info("sockname")
    if info is not None and isinstance(info, (list, tuple)) and len(info) == 2:
        return (str(info[0]), int(info[1]))
    return None
```
If you change it to `return  ['', 0]` the problem goes away. This method directly populates the scope's server variable. As far as I can tell the variable sockname does not appear in anywhere in Uvicorn or Gunicorn.

**Comment by lovelydinosaur** [comment]
> This issue is very easy to produce and very easy to fix.

Any chance you could submit a pull request? That’ll help keep it at the top of my TODO list.

Thanks for the extra feedback either way.

**Comment by agronick** [comment]
Is that the best way to solve it. Does ['',0] make sense?

**Comment by lovelydinosaur** [comment]
I’ve no idea, not looked into it yet. But if there’s a potential fix, then seeing exactly what change it means & ensuring that it passes the test suite would be a great start. A failing test case that it resolves would be even better. Hopefully I’ll be in a position to review stuff on Monday and release a fix.

**Comment by jordaneremieff** [comment]
What would be a minimal consumer example to reproduce this in a channels project? I've tried re-producing using the [multichat](https://github.com/andrewgodwin/channels-examples/tree/master/multichat) example, but didn't see any issues in my initial test.

**Comment by agronick** [comment]
Maybe it needs to be run with Gunicorn behind a unix socket connection.
Where does sockname get set? I couldn't find it getting set anywhere.

**Comment by jordaneremieff** [comment]
@agronick 

The code in utils file relies on the [base transport](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseTransport.get_extra_info) behaviour and is used to set the [`server`](https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/websockets/websockets_impl.py#L50) attribute when the protocol's [connection_made](https://docs.python.org/3/library/asyncio-protocol.html#asyncio.BaseProtocol.connection_made) callback is triggered - it is later used in the [`scope`](https://github.com/encode/uvicorn/blob/master/uvicorn/protocols/websockets/websockets_impl.py#L91) definition.

What specific run command/settings or deployment configuration are you using?

**Comment by felipe3dfx** [comment]
@erm Im have following deploy configuration

requirements.txt
```
Django==2.1.3
channels==2.1.5
channels_redis==2.3.2
gunicorn==19.9.0
uvicorn==0.3.21
```

gunicorn.conf
```
d /run/gunicorn 0755 deploy deploy -
```

gunicorn.service
```
[Unit]
Description=gunicorn daemon
Requires=gunicorn.socket
After=network.target

[Service]
PIDFile=/run/gunicorn/pid
User=deploy
Group=deploy
RuntimeDirectory=gunicorn
WorkingDirectory=/home/deploy/xxxx/
ExecStart=/usr/local/bin/gunicorn app.asgi:application --worker-class uvicorn.workers.UvicornWorker --pid /run/gunicorn/pid --bind unix:/run/gunicorn/socket --workers 4
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s TERM $MAINPID
PrivateTmp=true
Restart=always

[Install]
WantedBy=multi-user.target
```
gunicorn.socket
```
[Unit]
Description=gunicorn socket

[Socket]
ListenStream=/run/gunicorn/socket

[Install]
WantedBy=sockets.target
```
nginx
```
limit_req_zone $binary_remote_addr zone=one:10m rate=2r/s;

map $http_upgrade $connection_upgrade {
    default upgrade;
    '' close;
}

upstream app_server {
    server unix:/run/gunicorn/socket fail_timeout=0;
}

server {
    listen                      *:80 default_server deferred;
    server_name                 _ "";

    return                      444;
}

server {
    listen                      443 ssl http2;
    listen                      [::]:443 ssl http2;
    server_name                 xxxx.com;

    include                     ssl_params;

    add_header                  Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
    add_header                  X-Frame-Options DENY always;
    add_header                  X-Content-Type-Options nosniff always;
    add_header                  X-XSS-Protection "1; mode=block" always;
    charset                     utf-8;

    client_max_body_size        10m;
    client_body_buffer_size     128k;

    location /.well-known/acme-challenge {
        root /var/www/html;
    }

    location /favicon.ico {
        alias /home/deploy/xxxxx/static/img/favicon.png;
        expires max;
    }

    location /static/ {
        alias /home/deploy/xxxxx/static/;
        expires max;
    }

    location /uploads/ {
        alias /home/deploy/xxxxx/uploads/;
        expires max;
    }

    location /apple-app-site-association {
        alias /home/deploy/xxxxx/static/apple-app-site-association;
        expires max;
    }

    location /.well-known/assetlinks.json {
        alias /home/deploy/xxxxx/static/assetlinks.json;
        expires max;
    }

    location /OneSignalSDKUpdaterWorker.js {
        alias /home/deploy/xxxxx/static/vendor/OneSignalSDKUpdaterWorker.js;
        expires max;
    }

    location /OneSignalSDKWorker.js {
        alias /home/deploy/xxxxx/static/vendor/OneSignalSDKWorker.js;
        expires max;
    }

    location / {
        limit_req               zone=one burst=50 nodelay;

        proxy_http_version      1.1;

        proxy_buffering         off;
        proxy_redirect          off;

        proxy_set_header        Connection $connection_upgrade;
        proxy_set_header        Host $http_host;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Host $server_name;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Scheme $scheme;

        proxy_pass              http://app_server;
    }
}
server {
    listen                      80;
    listen                      [::]:80;
    server_name                 xxxx.com;

    return                      301 https://xxxx.com$request_uri;
}
```

**Comment by jordaneremieff** [comment]
@felipe3dfx would you be able to provide a more minimal example case where this occurs?

I was unable to reproduce the error with the following configuration using gunicorn (with the uvicorn worker), nginx, and a Channels application:

**nginx_site.conf**

```
upstream app {
    server unix:/run/gunicorn/socket fail_timeout=0;
}

server {

    listen 5000;
    server_name 127.0.0.1;

    location / {
        proxy_pass http://app;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_redirect off;
    }
}
```
**Run command:**

```
gunicorn multichat.asgi:application --worker-class uvicorn.workers.UvicornWorker --pid /run/gunicorn/pid --bind unix:/run/gunicorn/socket --workers 4
```

**Comment by felipe3dfx** [comment]
@erm I have the error over deployed server (Ubuntu server 18.04.1), locally works fine.

consumers.py
```
from asgiref.sync import async_to_sync
from channels.generic.websocket import AsyncJsonWebsocketConsumer
from channels.layers import get_channel_layer
from raven.contrib.django.models import get_client


_client = get_client()


BRAND_GROUP = 'BRAND-{id}-GROUP'

WS_VISIT_COUNT_SLUG = 'visit-count'

WS_SLUG_LIST = [
    WS_VISIT_COUNT_SLUG,
]


@_client.capture_exceptions
def send_payload(group, **kwargs):
    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.group_send)(group, {
        'type': 'general.payload',
        'content': kwargs,
    })


class Consumer(AsyncJsonWebsocketConsumer):
    @_client.capture_exceptions
    async def connect(self):
        slug = self.scope['url_route']['kwargs']['slug']
        user = self.scope['user']

        if slug in WS_SLUG_LIST:
            if user.is_brand_manager:
                await self.channel_layer.group_add(
                    BRAND_GROUP.format(id=user.brand.id),
                    self.channel_name
                )

            await self.accept()
        else:
            await self.close()

    @_client.capture_exceptions
    async def receive_json(self, content):
        slug = self.scope['url_route']['kwargs']['slug']
        user = self.scope['user']

        if slug in WS_SLUG_LIST:
            if user.is_brand_manager:
                await self.channel_layer.group_send(
                    BRAND_GROUP.format(id=user.brand.id),
                    {
                        'type': 'general.payload',
                        'content': content,
                    },
                )

    @_client.capture_exceptions
    async def disconnect(self, code):
        slug = self.scope['url_route']['kwargs']['slug']
        user = self.scope['user']

        if slug in WS_SLUG_LIST:
            if user.is_brand_manager:
                await self.channel_layer.group_discard(
                    BRAND_GROUP.format(id=user.brand.id),
                    self.channel_name
                )

    # Handler
    @_client.capture_exceptions
    async def general_payload(self, event):
        await self.send_json(event['content'])
```

routing.py
```
from django.urls import path

from channels.auth import AuthMiddlewareStack
from channels.routing import ProtocolTypeRouter
from channels.routing import URLRouter
from channels.security.websocket import AllowedHostsOriginValidator

from app.consumers import Consumer


application = ProtocolTypeRouter({
    'websocket': AllowedHostsOriginValidator(
        AuthMiddlewareStack(
            URLRouter([
                path('<slug:slug>/', Consumer),
            ])
        )
    ),
})
```

**Comment by agronick** [comment]
Its really easy to see how this is happening. `get_local_addr(transport)` returns None if the sockname key is not set. You just follow that code to where it gets set on the scope and its taking [0] from None. What should that function return when sockname is not set (it appears to never be set) instead of None?

**Comment by jordaneremieff** [comment]
What is a simple means of reproducing the issue in order to debug/test the solution? According to the ASGI [spec](https://asgi.readthedocs.io/en/latest/specs/www.html#websocket), the  `server` field is optional and defaults to `None`. It may be clear what is happening, but we need a way to reproduce the behaviour to determine a generic solution.
