### ISSUE TITLE
`CancelledError` raised on app startup in Argo CD

### ISSUE THREAD

**Issue by ishaan-mehta** [Kludex/uvicorn#2509]
I have a FastAPI app that uses `uvicorn`, and when I run locally with Docker on `colima`, I never encounter this error, but when I run that same app in Argo CD, I keep seeing the following error and the app immediately shuts down:
```
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/starlette/routing.py", line 700, in lifespan
    await receive()
  File "/usr/local/lib/python3.12/site-packages/uvicorn/lifespan/on.py", line 137, in receive
    return await self.receive_queue.get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/queues.py", line 158, in get
    await getter
asyncio.exceptions.CancelledError
```

(This is transient, however — very rarely, the app does manage to get past this and start without issue.)

As far as I can tell, this error is never supposed to actually surface to the user. How can I solve this? Is this an issue with `uvicorn`? An issue with `starlette`? (I am not using Ctrl-C or interacting with the app at all, which I have seen suggested on similar discussions online.)

_Originally posted by @ishaan-mehta in https://github.com/encode/uvicorn/discussions/2495_

**Comment by tonnico** [comment]
I see a similar problem in my setup.

Maybe it is an issue with the latest websockets major release?
On my test setup a downgrade to `websockets==13.1` will fix the issue.

**Comment by hunter2009pf** [comment]
same problem, how to fix it?

**Comment by Kludex** [comment]
Please create a discussion with an MRE.

**Comment by uwu-420** [comment]
@ishaan-mehta it's not quite the same as your situation, but I stumbled over similar symptoms when shutting down my app with ctrl+c in the terminal. For context, I use some runner that starts the python process of the app and on ctrl+c it forwards the SIGINT to the app process but the terminal also sends SIGINT to the app process so it receives it twice in a short amount of time. If I understand correctly, uvicorn will try to gracefully shut down on the first SIGINT but on the second SIGINT it just crashes ungracefully. Since there is not much time between the two SIGINTs we get this error.

I'd argue that this is desirable behavior from uvicorn, i.e. trying to gracefully shut down on the first press of ctrl+c but if that takes too long and you press ctrl+c again you get the ungraceful shutdown.

Not sure if something similar happens in your situation, but I maybe it's still a useful idea to consider.
