### ISSUE TITLE
Server sporadically closes websocket connection

### ISSUE THREAD

**Issue by woky** [Kludex/uvicorn#258]
I'm developing an application where logs are sent to server via websockets, where they are stored to Redis queue. The client program is written in Go and uses [gorilla's websocket library](github.com/gorilla/websocket). For the server, I chose [Quart](https://gitlab.com/pgjones/quart) library and initially [Hypercorn](https://gitlab.com/pgjones/hypercorn) as ASGI server, but then I switched to Uvicorn, because I encountered an issue with Hypercorn (which I have to report yet). When I was testing both the client and the server, the server always closed the connection at some point and client failed on broken pipe.

I was able to reproduce this issue with this simple server:
```
from quart import Quart, websocket
app = Quart(__name__)
@app.websocket('/')
async def ws():
    while True:
        msg = await websocket.receive()
        print(msg.strip())
```
and [websocat](https://github.com/vi/websocat). The print to terminal _simulates_ work on server (i.e. send to Redis in my case).

In first terminal I run the server:
```
uvicorn --debug --port 8001 server:app
```

In second terminal I monitor the connection:
```
watch -n0.5 ss -tpn dport 8001 or sport 8001
```

In third terminal I feed the server with data:
```
base64 </dev/urandom | pv | head -c1G | websocat ws://localhost:8001/
```

In almost all cases the server closed connection at 166 MiB and client failed on broken pipe[1]. I've also tried to send the data with [ws](https://github.com/hashrocket/ws), which apparently uses much smaller socket send queue, but I wasn't able to reproduce the issue with it. My client program however doesn't send data as fast as this test case does, so it doesn't have to be related to how fast the client is sending data.

I've also run this the server with Hypercorn and it received the whole gigabyte successfully.

I've put the above snippets in Git repository here: https://github.com/woky/python-ws-server-quart

[1] The websocat actually says
```
websocat: WebSocketError: I/O failure
websocat: error running
```

---

During the testing, I've also encountered this output from uvicorn, but it only happened once and I don't know how to reproduce it:

```
ERROR: Task exception was never retrieved
future: <Task finished coro=<ASGIWebsocketConnection.handle_messages() done, defined at /home/woky/.local/share/virtualenvs/collector-6rwrPP7y/lib/python3.7/site-packages/quart/asgi.py:108> exception=InvalidStateError('invalid state')>
Traceback (most recent call last):
  File "/home/woky/.local/share/virtualenvs/collector-6rwrPP7y/lib/python3.7/site-packages/quart/asgi.py", line 110, in handle_messages
    event = await receive()
  File "/home/woky/.local/share/virtualenvs/collector-6rwrPP7y/lib/python3.7/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 222, in asgi_receive
    data = await self.recv()
  File "/home/woky/.local/share/virtualenvs/collector-6rwrPP7y/lib/python3.7/site-packages/websockets/protocol.py", line 441, in recv
    self._put_message_waiter.set_result(None)
asyncio.base_futures.InvalidStateError: invalid state
```

**Comment by lovelydinosaur** [comment]
We have two alternative websocket implementations.
The best way to progress this issue would be to start by determining if you can replicate the issue with `--ws wsproto` or not.
Once we've got an answer to that, I ought to be able to look into it further.

**Comment by euri10** [comment]
@woky I can recreate, with a starlette ws echo app and using uvicorn with defaults (ie websockets implementation)

it seems to me the closing is time-related since it's always terminating after 50s (2*20s ping/pong + 10s close timeout ?)

The issue arises on the simplest websockets echo server below, it also closes at 50s.

```
import asyncio
import websockets

import logging
wslogger = logging.getLogger('websockets')
wslogger.setLevel(logging.DEBUG)
wslogger.addHandler(logging.StreamHandler())

async def echo(websocket, path):
    async for message in websocket:
        await websocket.send(message)

asyncio.get_event_loop().run_until_complete(
    websockets.serve(echo, '127.0.0.1', 8000))
asyncio.get_event_loop().run_forever()
```

I can't recreate on the wsproto implementation and can pass the whole gigabyte just fine, albeit it takes time :)

A trace log of what's happening at the end, seems like we're missing a pong, but since the little server above has the same issue I'm not sure if it shouldn't be reported upstream ? thoughts /cc @florimondmanca 

```
TRACE:    127.0.0.1:51762 - ASGI [2] Receive {'type': 'websocket.receive', 'text': '<77 chars>'}
TRACE:    127.0.0.1:51762 - ASGI [2] Send {'type': 'websocket.send', 'text': '<95 chars>'}
server > Frame(fin=True, opcode=1, data=b'Message text was: NIscZs7L8kYJtW0wtQRJbS0cBRb0wh2/faldK27aPRIorUnhxm7Rc485TZRO+K1Nukd7HCobMAYh\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'9uOsghxACDBPzcFbdTZ1s7YQZxKajTNyi6yTBkMkAkFJrONUFRjv5yjj2C9YtPUSX816rMx1ZZ+g\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'VKPjvQKuAHm/XzRVfQyON5DVWCmM8rxTMU3MYc4t4k7YZ3j3ytiPLjghs+NuzEJ3MKVPKQqO4Qi2\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'agHT0G5UrR/dKYVB0b7jeS5ApP//QqIJpTEd2beuTTyW8AnWW9m0Y80sfs533yM7ECUg15YvWfmp\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'I2rBzWQDc5nxVQ4vRjCgpqZ40LxZNT/NqRIt7k6vjtxjR8Zo8XPz5YBC2ITHYlLsWdTFQyhPmoGg\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'Hc+OR9liCnfrD+/sHTrIUmBN9+04j4TensMJVQdKwoQ2SkG2xABDN0cegMC4tTGmE8W1STuSPPTS\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'Hfrg5bL3+5HpS+KyxxQ0O0dFqyqK9AOxDwyPUhCJ/9dCAC5HYQNxEUmUhSNs05aV0M9QC5mFnGrZ\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'07K0SWmRA2TIv/xeDAI2p2yHiGZOc8tOtNvTHbC7ivij8BvjC6WH6GrU5bmeqFxAXTadHuDd7fcN\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'FfKiyiWfkJJUAOdFv9OpxzSgPCbnRfL10ZKdhFhLtb5Zmt3HLZC0/IyjX/R9JoMHaO6NAR+aYrRH\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'cmRpGQ1nM3sN20Qjnri443VBrL61XrOIpWMfXTI8W7ugM71GuOArZz2bNWmYZsz6AnUeCDz7ih2/\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'XnNhM2SzvfpZZduZS1RsI/BFXKUu76+YUNu09qSQmwJnd0hE2YUzTfSn7P6T29HZotjl9/EUzhga\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'nM5CBUMKSlLNFQgd9fBFIhBxt7HDtaxEedwV7DxmR3lHg529JmGTdPwmRQZokok90BvcUxFI8AkC\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'NCXixvqz3kEu82EtB//LWXC8uGLssAgAJ/C3oJdDxyKxeDqMY1w5Zgw0WRF68iyXBbBrHzvvanch\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'2ty5HQ5lsqYFOwrGvGnzMkPrEGkZMFUqr6WriGCqdulflLm5q3z8EYHrK2uwQtWbDTvm9LCPui9h\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'757myIreofYxnWMsSpeDKe0UOIF4hRWOS7t+nnunFHDOGafr87RazlxTWuekdTr4zDQAdj21PUia\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'MBVuD2SlyviGblJlLO9mTZKTUBY7PfOE1DaCUc4WYHf0K9rFBp7b3EfsKZuhgw4Eis6oFcrXJhM0\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'1GoUZV8BKfeAsRW4L3QVdVdzPD6uRhp3KrvjCmGvxGwjrDYFJh2M3PrMZ9q9RE5sR1jl9i7jhhF0\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'I6GAh7JD+2uXpKlAAciKStwmaAvzTAtiJWzAk8iWWDz30u+WvYiy/tKuKP+7LjaA7AyziWJ8uXg+\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'S5puxdszi6M75HH7ufK7JyNgJAJZ5QJzhF7MXup3bGBLg4k/8egzS5HymG0sl+j2WFAYwOODQVFP\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'EWF1Mid3C4/xrdfkpeBnnLj75/NDX4ccGrq8oomKmu6acNxqMDBWwPqQRgSO6Wvi1wYvKmLWNCYr\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'htMYVD5WO/HM/XzVT2KzJnrkS0bqEr0FOVFvTRClqKXxs9wSEhQ1XBR2c3Pm+NqVurKfafQWVXiY\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'M+ICNs/WJXzrH6F7ExyHnxI7bQN1LVqaLrvQTFwTMludGCZ8nQVK0IPpb9lnBlOnGBXhJp+gDiuM\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'FJa+QviWPa1op5neAT1MrqXmz/3Hx+CjqmBBuboeneqRYwULusSjyV5QJIok9jkokwaFQjv7v+M3\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'6Xb/MVDL5hxTgXfwHaTzgflTRVTJMZdKnQJpMFtKaKcRXzPJZ/rj2lfT5uf86GaJAZi4RLAil5Xx\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'q/1wS+DXgr6KqB8mDRB0N6d+RSe3HTMZdx/iCCaLazq1Tl9EIvzCZ3C9pu1ENJcEQ/MHDZdo9C5G\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'N2Qy/tsxGvNcjL+sSJYtrbs8ga1hZ5GIcfZSuK9sxDRtVN06iWKoyuuUWYpxkv+cBviR+sIOMRu9\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'CRGlD5FhhhgcOEuW0rZDD6WNf4vIWqdXH8uL1wtTyRq34Z/IwO17qdCcxZEAsnNA7zpJvwzYfU2O\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'jnvdl0TvRvY0wv9+bTPKWb7IO41oTZZNh0RTEqpA1plMxaJSKkvuHGM4fJ4h3ABaln1twwaPlWnW\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'lR6ZSpH3zdKVprUolQA+l8E0QtBZbo3HxnGZTS8bNoiPwJZE8mn+qyWBkT0Zfe+a5TLmLUHQrBhx\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'6pP2ESfKOTpCM6I7aQWjwFXzxxOvjEH4WO/+blxqVNShiVklx2dqzrbF94glUcLHS8VKaypR895K\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'OfujxoCqPyxCZuraY1ZgpXStTLbmMiEGEG/zSbn+wvBsR5/Hw49S0mu8ML+4JRuq7Rs1nQa3/YbD\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'HknwpuEjxUj7n3Fp8cno0p9MalOVeh2NmYtQMAl+4scB1Sd3si9TUNntaMRiHFduR8BqVqcpplq5\n', rsv1=False, rsv2=False, rsv3=False)
server < Frame(fin=True, opcode=1, data=b'MePwXLRqwWPhsNWX7J6FWqT9jOeQh5VZQhJl06glm/lT1IDbbvH/XsKE/tnQmtEB0QBKH30x5mkl\n', rsv1=False, rsv2=False, rsv3=False)
server ! timed out waiting for pong
server ! failing OPEN WebSocket connection with code 1011
server - state = CLOSING
server > Frame(fin=True, opcode=8, data=b'\x03\xf3', rsv1=False, rsv2=False, rsv3=False)
TRACE:    127.0.0.1:51762 - ASGI [2] Receive {'type': 'websocket.receive', 'text': '<77 chars>'}
TRACE:    127.0.0.1:51762 - ASGI [2] Send {'type': 'websocket.send', 'text': '<95 chars>'}
server x half-closing TCP connection
server ! timed out waiting for TCP close
server x closing TCP connection
server - event = connection_lost(None)
server - state = CLOSED
server x code = 1006, reason = [no reason]
server - aborted pending ping: 052598dc
code = 1006 (connection closed abnormally [internal]), no reason
TRACE:    127.0.0.1:51762 - ASGI [2] Receive {'type': 'websocket.disconnect', 'code': 1006}
TRACE:    127.0.0.1:51762 - ASGI [2] Completed
```

**Comment by euri10** [comment]
~~or simply using this pipe through websocat blocks the pong the client should send, not sure we're not digging a rabbit hole here~~
well using `websocat -s 8000` as a server and we can pass the whole gb fine

**Comment by euri10** [comment]
using this simple client I cant reproduce:
```
import asyncio
import base64
import os

import websockets


async def hello():
    uri = "ws://127.0.0.1:8000"
    async with websockets.connect(uri) as websocket:
        while True:
            input = base64.b64encode(os.urandom(32)).decode()
            await websocket.send(input)
            rec = await websocket.recv()
            print(f"< {rec}")

asyncio.get_event_loop().run_until_complete(hello())
```
I'm now convinced that the `base64 </dev/urandom | pv | head -c1G | websocat ws://localhost:8001/` does fail with websockets implementation as it does not send pings correctly, if you do `base64 </dev/urandom | pv | head -c1G | websocat -v ws://127.0.0.1:8000 --ping-interval=10` and look at websockets little echo server logs from above, it nevers get a ping (whereas you get pings in the case of the little websockets client)



 so I'm going to close it for now, dont hesitate to add more details if you feel like I shouldn't have
