### ISSUE TITLE
Low level server

### ISSUE THREAD

**Issue by JoseKilo** [Kludex/uvicorn#265]
Is it possible to create a server without launching the asyncio loop at the same time ? I've been checking the code in main.py, `Server.run()` seems to be what I need more or less, but it calls `loop.run_forever()` at the end.

I'm more familiar with `aiohttp`, which supports something like this: https://aiohttp.readthedocs.io/en/stable/web_lowlevel.html#run-a-basic-low-level-server

Basically, I would like to execute other coroutines on the same loop. Using the `main()` function from that example, I'm able to do something like this:

```python
async def foo():
    for i in itertools.count():
        print(i)
        await asyncio.sleep(1)


if __name__ == "__main__":
    loop = asyncio.get_event_loop()

    tasks = [
        loop.create_task(main()),
        loop.create_task(foo()),
    ]

    try:
        loop.run_forever()
    except KeyboardInterrupt:
        for task in tasks:
            task.cancel()

    loop.close()
```

What would be the equivalent of that `main()` function using `uvicorn` (if any) ?
Also, if you think this is not a good idea / good practice for some reason, please let me know.

**Comment by JoseKilo** [comment]
Using the latest changes I was able to put a working example together.

Handling the signals is a bit tricky. If you need to integrate the server with a bigger application you probably want to control the signals yourself.

Note that it doesn't support a second Ctrl-C to force exit like the original Server. And I haven't added windows signals just to make it more simple. But it shouldn't be difficult to control those. 

Let me know what you think.

```python
import asyncio
import itertools
import signal
import sys

import starlette.applications
import starlette.responses
import uvicorn.config
from uvicorn.main import Server as OriginalServer


def install_signal_handlers(loop):
    for sig in (signal.SIGINT, signal.SIGTERM):
        loop.add_signal_handler(sig, sys.exit, sig)


class Server(OriginalServer):

    def install_signal_handlers(self):
        pass

    async def run(self):
        config = self.config
        if not config.loaded:
            config.load()

        self.loop = config.loop_instance
        self.logger = config.logger_instance
        self.lifespan = config.lifespan_class(config)

        await self.startup()
        self._task = self.loop.create_task(self.main_loop())

    async def stop(self):
        self.should_exit = True
        await self._task
        await self.shutdown()


def make_server(loop):
    app = starlette.applications.Starlette()

    @app.route('/')
    async def homepage(request):
        return starlette.responses.JSONResponse({'hello': 'world'})

    config = uvicorn.config.Config(
        app,
        loop=loop,
    )

    return Server(config=config)


async def foo():
    for i in itertools.count():
        print(i)
        await asyncio.sleep(1)


def main():
    loop = asyncio.get_event_loop()

    install_signal_handlers(loop=loop)
    server = make_server(loop=loop)

    tasks = [
        loop.create_task(server.run()),
        loop.create_task(foo()),
    ]

    try:
        loop.run_forever()
    except (KeyboardInterrupt, SystemExit):
        print('Shutting down')
        loop.run_until_complete(server.stop())

        for task in tasks:
            task.cancel()

        # Give control back to the loop so that the tasks are actually
        # cancelled and we don't get task pending errors.
        loop.run_until_complete(asyncio.sleep(0))

    loop.close()
    print('Shut down cleanly.')


if __name__ == '__main__':
    main()
```

**Comment by lovelydinosaur** [comment]
Looks like quite a lot of code, but I don't really know what you're trying to do here.

The following *almost* works cleanly from the console...

```python
>>> from uvicorn.main import Config, Server
>>> import asyncio
>>> config = Config(app=None)
>>> server = Server(config)
>>> asyncio.get_event_loop().run_until_complete(server.run())
INFO: Started server process [12626]
INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
^C
INFO: Shutting down
INFO: Finished server process [12626]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 549, in run_until_complete
    self._check_closed()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 469, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

That's more the sort of level I'm thinking of documenting, except that we'd need an variant that is essentially `async run(self)`, and that doesn't setup the event loop, or stop it.

If we factored out a `Config.setup_event_loop()` from the rest of the `Config.load()` then perhaps we could have something like this...

```python
    def main(self)
        loop = self.config.setup_event_loop()
        loop.run_until_complete(self.run())
        loop.stop()

    async def run(self):
        process_id = os.getpid()

        self.install_signal_handlers()

        config = self.config
        if not config.loaded:
            config.load()

        self.logger = config.logger_instance
        self.lifespan = config.lifespan_class(config)

        self.logger.info("Started server process [{}]".format(process_id))
        await self.startup()
        await self.main_loop()
        await self.shutdown()
        self.logger.info("Finished server process [{}]".format(process_id))
```

Then `server.main()` is the thread-blocking, deal with the event loop itself entry point, and `server.run()` is the async variant.

**Comment by JoseKilo** [comment]
I have followed that approach and prepared a PR: https://github.com/encode/uvicorn/pull/300

My example becomes much simpler: no need to modify the Server class.
And your example runs without that RuntimeError.

I have also added a check for `config.install_signal_handlers` so that I can configure the signals globally.
