### ISSUE TITLE
HEAD request raise error with h11

### ISSUE THREAD

**Issue by JoseKilo** [Kludex/uvicorn#269]
I'm using the same example from the Readme but running with h11:

```bash
uvicorn --http h11 app:App
```

When I make a HEAD request, I get this error:

```bash
> uvicorn --http h11 app:App
INFO: Started server process [509]
INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO: ('127.0.0.1', 43588) - "HEAD / HTTP/1.1" 200
ERROR: Exception in ASGI application
Traceback (most recent call last):
  File "/home/merlin/workspace/uvicorn_test_2/.venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 394, in run_asgi
    result = await asgi(self.receive, self.send)
  File "./app.py", line 19, in __call__
    'body': b'Hello, world!',
  File "/home/merlin/workspace/uvicorn_test_2/.venv/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 486, in send
    event = h11.Data()
  File "/home/merlin/workspace/uvicorn_test_2/.venv/lib/python3.6/site-packages/h11/_events.py", line 39, in __init__
    .format(field, self.__class__.__name__))
TypeError: missing required kwarg data for Data
^CINFO: Stopping server process [509]
```
```

**Comment by lovelydinosaur** [comment]
Great work on these! Nice concise issue descriptions, and pull requests demonstrating what needs to change. Thanks so much. 😄
