### ISSUE TITLE
Crash when using --reload and SSL certificate

### ISSUE THREAD

**Issue by nymous** [Kludex/uvicorn#352]
Using the example code
```python
async def app(scope, receive, send):
    assert scope['type'] == 'http'

    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ],
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })
```

with a certificate created by `mkcert` in the current directory, and running 
`uvicorn ssl:app --reload --ssl-keyfile=./uvicorn.localhost-key.pem --ssl-certfile=./uvicorn.localhost.pem` results in the following error:

<details>
<summary>Stacktrace</summary>

```
INFO: Uvicorn running on https://127.0.0.1:8000 (Press CTRL+C to quit)
INFO: Started reloader process [31388]
Traceback (most recent call last):
  File "/tmp/tmp.zVyoktn22U/.venv/bin/uvicorn", line 11, in <module>
    load_entry_point('uvicorn==0.7.0', 'console_scripts', 'uvicorn')()
  File "/tmp/tmp.zVyoktn22U/.venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/tmp.zVyoktn22U/.venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/tmp/tmp.zVyoktn22U/.venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/tmp.zVyoktn22U/.venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/tmp/tmp.zVyoktn22U/.venv/lib/python3.7/site-packages/uvicorn/main.py", line 256, in main
    run(**kwargs)
  File "/tmp/tmp.zVyoktn22U/.venv/lib/python3.7/site-packages/uvicorn/main.py", line 271, in run
    supervisor.run(server.run, sockets=[socket])
  File "/tmp/tmp.zVyoktn22U/.venv/lib/python3.7/site-packages/uvicorn/supervisors/statreload.py", line 34, in run
    process.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/usr/lib/python3.7/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle SSLContext objects
```
</details>

*Environment:*
`python -V`: Python 3.7.3
`uvicorn`: 0.7.0
`uname -a`: `Linux architect 5.0.9-arch1-1-ARCH #1 SMP PREEMPT Sat Apr 20 15:00:46 UTC 2019 x86_64 GNU/Linux`

**Comment by lovelydinosaur** [comment]
Okay - looks like loading the SSL context ought to move out of `Config.__init__` and into `Config.load()`.

That way the `SSLCotext` instance won't be created until after the forking occurs.

Want to give that a try on a codebase locally, and then consider submitting a pull request?

**Comment by yano3nora** [comment]
I have the same problem using self-signed certificates in local for development.
Has this problem been resolved?
