### ISSUE TITLE
--reload flag causes failure to start

### ISSUE THREAD

**Issue by microbug** [Kludex/uvicorn#374]
I'm new to Uvicorn so this could be wrong. I've tested it bare metal on my laptop (macOS 10.14.5, python3 from Homebrew) and also in a docker container to make sure it's not just my machine. (Docker runs in a Linux VM on macOS.) Steps to reproduce:

```
docker run -it -p 8000:8000 ubuntu bash
apt update
apt install --yes python3 python3-dev python3-pip neovim
pip3 install uvicorn
nvim example.py  # paste in the example code from README.md
export LC_ALL=C.UTF-8  # fix system encoding -- this is not required if you run this in a proper VM or on bare metal
export LANG=C.UTF-8
uvicorn example:app  # this works -- visit 127.0.0.1:8000
uvicorn example:app --reload  # this causes an error, see below
```

Immediately after executing `uvicorn example:app --reload`, I get this traceback and execution stops:
```
root@4a74f603e723:/# uvicorn example:app --reload
Traceback (most recent call last):
  File "/usr/local/bin/uvicorn", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/main.py", line 257, in main
    run(**kwargs)
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/main.py", line 270, in run
    socket = config.bind_socket()
  File "/usr/local/lib/python3.6/dist-packages/uvicorn/config.py", line 222, in bind_socket
    protocol_name = "https" if self.ssl else "http"
AttributeError: 'Config' object has no attribute 'ssl'
```

**Comment by kthwaite** [comment]
Same issue here.

I think that commit [`5463339`](https://github.com/encode/uvicorn/commit/5463339475473efdec0517223515e4a3c171edfe) may have broken both the --debug and --workers flags by moving the initialization of `Config.ssl` out of `__init__` and into the `load()` method. Attempt to use either existing projects or a minimal example as per 'Quickstart' results in the same AttributeError:
```
Traceback (most recent call last):
  File "/home/kthwaite/.virtualenvs/test/bin/uvicorn", line 10, in <module>
    sys.exit(main())
  File "/home/kthwaite/.virtualenvs/test/local/lib/python3.6/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kthwaite/.virtualenvs/test/local/lib/python3.6/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kthwaite/.virtualenvs/test/local/lib/python3.6/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kthwaite/.virtualenvs/test/local/lib/python3.6/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kthwaite/.virtualenvs/test/local/lib/python3.6/dist-packages/uvicorn/main.py", line 257, in main
    run(**kwargs)
  File "/home/kthwaite/.virtualenvs/test/local/lib/python3.6/dist-packages/uvicorn/main.py", line 274, in run
    socket = config.bind_socket()
  File "/home/kthwaite/.virtualenvs/test/local/lib/python3.6/dist-packages/uvicorn/config.py", line 222, in bind_socket
    protocol_name = "https" if self.ssl else "http"
AttributeError: 'Config' object has no attribute 'ssl'
```

This appears to be because [`Config.bind_socket()` is called before `Server.run()`](https://github.com/encode/uvicorn/blob/a7ddb2987f57ab0f7acedef70f49b0ff323618eb/uvicorn/main.py#L270) if either the `workers` or `debug` options are active; and because  `Server.run()` calls `Config.load()` - [which now populates the `Config.ssl` attribute](https://github.com/encode/uvicorn/blob/a7ddb2987f57ab0f7acedef70f49b0ff323618eb/uvicorn/config.py#L147) - `Config.ssl` doesn't exist at that point.

**Comment by gnat** [comment]
+1 Just started happening. Issue does not exist in 0.7.2

both --reload and --debug flags are affected.

**Comment by lovelydinosaur** [comment]
Meh. What's our options here - do we just have to revert #362 / #352?

**Comment by kthwaite** [comment]
Does `Config.bind_socket` need an actual SSL context, or just a check equivalent to the one being made in `Config.load`? i.e. am I right in thinking that, because the SSL context won't be used until (after) `create_server` is called, you can just change the check in L222 of config.py to
```python
protocol_name = "https" if self.ssl_keyfile or self.ssl_certfile else "http"
```

Apologies if I'm barking up the wrong tree here!

**Comment by lovelydinosaur** [comment]
@cthwaite - Looks like that might be a good call... https://github.com/encode/uvicorn/pull/375

**Comment by lovelydinosaur** [comment]
Bumped 0.8.1 to PyPI - wanna confirm how we're looking anyone?

**Comment by lovelydinosaur** [comment]
Looks good to me - going to close this off pending any further issues.

**Comment by lovelydinosaur** [comment]
It's a bit telling that this wasn't caught at all in our test suite.

We'll probably want to have at least a couple of proper full-on integration tests that *fully* run the uvicorn command line client within a subprocess.
