### ISSUE TITLE
websocket client inside app failed with uvicorn

### ISSUE THREAD

**Issue by mozartilize** [Kludex/uvicorn#393]
I have a django app integrates with django channels.

And I have a websocket client (using wsproto) inside the app. It workds fine with daphne but somehow it does not with uvicorn. It failed when trying to connect to websocket server.

I dont have full traceback now, but the error it shows is:

`h11._util.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE`

**Comment by lovelydinosaur** [comment]
I'd be happy to dig into this, but the issue isn't sufficiently informative to act on right now.

What's the simplest possible way to reproduce this?

> I dont have full traceback now

Okaty would you be able to reproduce, and show the full traceback?

**Comment by mozartilize** [comment]
ok, i'll give you an example on weekend

**Comment by mozartilize** [comment]
Just got some free time tonight and setup an example for this.

Repo here: https://github.com/mozartilize/uvicorn-test

How to test:

Open one tab and create a websocket to server:

```javascript
ws = new WebSocket('ws://localhost:8000/ws/todos')
ws.addEventListener('message', function(e) { console.log(e) })
```

Another tab open http://localhost:8000/todos/new then add new todo

With daphne `daphne -b localhost -p 8000 foo.asgi:application`, ws receives event as expected
while with uvicorn `uvicorn --lifespan off --ws wsproto --port 8000 foo.asgi:application`, it got error on server side:

```
Sending 160 bytes
WARNING: Invalid HTTP request received.
Received 0 bytes (connection closed)
Internal Server Error: /todos/new
Traceback (most recent call last):
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/wsproto/handshake.py", line 112, in receive_data
    event = self._h11_connection.next_event()
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_connection.py", line 439, in next_event
    exc._reraise_as_remote_protocol_error()
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_util.py", line 72, in _reraise_as_remote_protocol_error
    raise self
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_connection.py", line 422, in next_event
    self._process_event(self.their_role, event)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_connection.py", line 238, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_state.py", line 253, in _fire_event_triggered_transitions
    .format(event_type.__name__, role, self.states[role]))
h11._util.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./todo/views.py", line 12, in new
    todo.save()
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/db/models/base.py", line 790, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "./todo/signals.py", line 63, in handle_todo_post_save
    net_recv(ws, conn)
  File "./todo/signals.py", line 32, in net_recv
    ws.receive_data(None)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/wsproto/__init__.py", line 43, in receive_data
    self.handshake.receive_data(data)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/wsproto/handshake.py", line 115, in receive_data
    "Bad HTTP message", event_hint=RejectConnection()
wsproto.utilities.RemoteProtocolError: Bad HTTP message
ERROR: Internal Server Error: /todos/new
Traceback (most recent call last):
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_state.py", line 249, in _fire_event_triggered_transitions
    new_state = EVENT_TRIGGERED_TRANSITIONS[role][state][event_type]
KeyError: <class 'h11._events.ConnectionClosed'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/wsproto/handshake.py", line 112, in receive_data
    event = self._h11_connection.next_event()
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_connection.py", line 439, in next_event
    exc._reraise_as_remote_protocol_error()
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_util.py", line 72, in _reraise_as_remote_protocol_error
    raise self
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_connection.py", line 422, in next_event
    self._process_event(self.their_role, event)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_connection.py", line 238, in _process_event
    self._cstate.process_event(role, type(event), server_switch_event)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_state.py", line 238, in process_event
    self._fire_event_triggered_transitions(role, event_type)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/h11/_state.py", line 253, in _fire_event_triggered_transitions
    .format(event_type.__name__, role, self.states[role]))
h11._util.RemoteProtocolError: can't handle event type ConnectionClosed when role=SERVER and state=SEND_RESPONSE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "./todo/views.py", line 12, in new
    todo.save()
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/db/models/base.py", line 790, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/django/dispatch/dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "./todo/signals.py", line 63, in handle_todo_post_save
    net_recv(ws, conn)
  File "./todo/signals.py", line 32, in net_recv
    ws.receive_data(None)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/wsproto/__init__.py", line 43, in receive_data
    self.handshake.receive_data(data)
  File "[...]/uvicorn-test/venv/lib/python3.7/site-packages/wsproto/handshake.py", line 115, in receive_data
    "Bad HTTP message", event_hint=RejectConnection()
wsproto.utilities.RemoteProtocolError: Bad HTTP message
```

**Comment by mozartilize** [comment]
btw, the websocket client was created in signals.py, it sends event after a todo created, I used client here because django channel_layer does not work with docker swarm multiple replicas

**Comment by euri10** [comment]
I'm going to close it for now @mozartilize , there's no way currently to see easily where the issue lies, having tested you test repo for a little time I found that just sending 2 bytes to the ws server fails in channels.
Let us know if you got a simpler example.


```
❯ PYTHONUNBUFFERED=1;DJANGO_SETTINGS_MODULE=foo.settings uvicorn --lifespan off --port 8000 --log-level=trace --ws=wsproto foo.asgi:application
INFO:     Started server process [13332]
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
TRACE:    127.0.0.1:39432 - Connection made
TRACE:    127.0.0.1:39432 - ASGI [1] Started scope={'type': 'websocket', 'asgi': {'version': '2.0', 'spec_version': '2.1'}, 'http_version': '1.1', 'scheme': 'ws', 'server': ('127.0.0.1', 8000), 'client': ('127.0.0.1', 39432), 'root_path': '', 'path': '/ws/todos', 'raw_path': '/ws/todos', 'query_string': b'', 'headers': '<...>', 'subprotocols': []}
TRACE:    127.0.0.1:39432 - ASGI [1] Receive {'type': 'websocket.connect'}
TRACE:    127.0.0.1:39432 - ASGI [1] Send {'type': 'websocket.accept', 'subprotocol': None}
INFO:     ('127.0.0.1', 39432) - "WebSocket /ws/todos" [accepted]
TRACE:    127.0.0.1:39432 - ASGI [1] Receive {'type': 'websocket.receive', 'text': '<2 chars>'}
TRACE:    127.0.0.1:39432 - ASGI [1] Raised exception
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/lotso/PycharmProjects/uvicorn-test/venv/lib/python3.8/site-packages/uvicorn/protocols/websockets/wsproto_impl.py", line 210, in run_asgi
    result = await self.app(self.scope, self.receive, self.send)
  File "/home/lotso/PycharmProjects/uvicorn-test/venv/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/home/lotso/PycharmProjects/uvicorn-test/venv/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 65, in __call__
    raise exc from None
  File "/home/lotso/PycharmProjects/uvicorn-test/venv/lib/python3.8/site-packages/uvicorn/middleware/message_logger.py", line 61, in __call__
    await self.app(scope, inner_receive, inner_send)
  File "/home/lotso/PycharmProjects/uvicorn-test/venv/lib/python3.8/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__
    await instance(receive, send)
  File "/home/lotso/PycharmProjects/uvicorn-test/venv/lib/python3.8/site-packages/channels/consumer.py", line 58, in __call__
    await await_many_dispatch(
  File "/home/lotso/PycharmProjects/uvicorn-test/venv/lib/python3.8/site-packages/channels/utils.py", line 59, in await_many_dispatch
    await task
asyncio.exceptions.CancelledError
```
