### ISSUE TITLE
TypeError: An asyncio.Future, a coroutine or an awaitable is required

### ISSUE THREAD

**Issue by najamansari** [Kludex/uvicorn#415]
Hi there,

We are using Uvicorn to serve a Django Channels based web sockets backend. I keep seeing the error below in Uvicorn's error.log:

```
[2019-08-28 18:08:10 +0000] [489] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/redacted/env/lib/python3.6/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 146, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
  File "/redacted/env/lib/python3.6/site-packages/uvicorn/middleware/asgi2.py", line 7, in __call__
    await instance(receive, send)
  File "/redacted/env/lib/python3.6/site-packages/channels/consumer.py", line 59, in __call__
    [receive, self.channel_receive], self.dispatch
  File "/redacted/env/lib/python3.6/site-packages/channels/utils.py", line 59, in await_many_dispatch
    await task
  File "/redacted/env/lib/python3.6/site-packages/channels/utils.py", line 51, in await_many_dispatch
    result = task.result()
  File "/redacted/env/lib/python3.6/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 226, in asgi_receive
    data = await self.recv()
  File "/redacted/env/lib/python3.6/site-packages/websockets/protocol.py", line 419, in recv
    return_when=asyncio.FIRST_COMPLETED,
  File "/usr/lib/python3.6/asyncio/tasks.py", line 311, in wait
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/usr/lib/python3.6/asyncio/tasks.py", line 311, in <setcomp>
    fs = {ensure_future(f, loop=loop) for f in set(fs)}
  File "/usr/lib/python3.6/asyncio/tasks.py", line 526, in ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable is '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```

I'm unable to figure out whether this issue is coming in from Uvicorn or Channels or something else. Any help would be much appreciated.

**Comment by flbraun** [comment]
I'm also struggling with this, https://github.com/encode/uvicorn/issues/244#issuecomment-493432296 is the only thing that has helped me so far.

**Comment by najamansari** [comment]
@Chiron1991 thanks! I will remove the `self.close()` call from my `connect` method and see if that fixes it

**Comment by lovelydinosaur** [comment]
Closing this as a duplicate of https://github.com/encode/uvicorn/issues/244
