### ISSUE TITLE
The gunicorn worker does not modify the signal handles.

### ISSUE THREAD

**Issue by tedyu002** [Kludex/uvicorn#464]
Uvicorn 0.9.0

In the uvicorn.workers.UvicornWorker, the init_signals is overridden
```
from gunicorn.workers.base import Worker

class UvicornWorker(Worker):
  ...
  def init_signals(self):
    pass
```

It makes the signal handler remains in master mode, not worker mode.
I dump the signal handler of SIGUSR1 from the request, it's the Arbiter.signal.
Is it a bug or some other consideration?

**Comment by andreportela** [comment]
I'm using UvicornH11Worker and I'm also having trouble to handle SIGINT for a small FastAPI app.

This apparently doesn't work on UvicornH11Worker.
```
@app.on_event('shutdown')
async def deallocate_resources():
    await aiologger.logger.shutdown()
    await aiokafka.producer.stop()
```

I get this exception instead:
```
[2019-10-31 09:59:00 -0400] [15903] [INFO] Worker exiting (pid: 15903)
[2019-10-31 09:59:00 -0400] [15892] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/work/virtual_environments/vendas_374/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/work/virtual_environments/vendas_374/lib/python3.7/site-packages/uvicorn/workers.py", line 55, in init_process
    super(UvicornWorker, self).init_process()
  File "/work/virtual_environments/vendas_374/lib/python3.7/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.run()
  File "/work/virtual_environments/vendas_374/lib/python3.7/site-packages/uvicorn/workers.py", line 64, in run
    loop.run_until_complete(server.serve(sockets=self.sockets))
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/work/virtual_environments/vendas_374/lib/python3.7/site-packages/uvicorn/main.py", line 359, in serve
    await self.shutdown(sockets=sockets)
  File "/work/virtual_environments/vendas_374/lib/python3.7/site-packages/uvicorn/main.py", line 480, in shutdown
    server.close()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 306, in close
    self._loop._stop_serving(sock)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/selector_events.py", line 562, in _stop_serving
    self._remove_reader(sock.fileno())
  File "/work/virtual_environments/vendas_374/lib/python3.7/site-packages/gunicorn/sock.py", line 38, in __getattr__
    return getattr(self.sock, name)
AttributeError: 'NoneType' object has no attribute 'fileno'
```
It was working when using just `$ uvicorn --reload`.

How should I handle SIGINT and others while using UvicornH11Worker?

**Comment by lakemist** [comment]
I also came across this while trying to restore the "reload" functionality in a dev environment while using uvicorn with gunicorn.

The following does work but I wouldn't use it outside if development:

```
from uvicorn.workers import UvicornWorker as BaseUvicornWorker

class UvicornWorker(BaseUvicornWorker):
    def init_signals(self):
        super(BaseUvicornWorker, self).init_signals()
```

What is reasoning for ignoring these signals in the uvicorn worker?

**Comment by euri10** [comment]
This seems related and fixed, please tell us if not the case
https://github.com/encode/uvicorn/issues/896
