### ISSUE TITLE
TypeError: __call__() missing 1 required positional argument: 'start_response' ?

### ISSUE THREAD

**Issue by scwall** [Kludex/uvicorn#483]
Hello, I recently decided to integrate Django Channel into one of my projects. I mainly use Django cookie cutter for my projects. After reading several documents, I could understand that the easiest integration was the use of uvicorn gunicorn, so I created my Routing file, my ASGI file, I created my workers etc... and everything works well locally (with the manage.py runserver command) now I try to use unicorn with uvicorn in production. So I added -k uvicorn.workers.UvicornWorker to my command. Here is the complete command:

`/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0.:5000 --chdir=/app -k uvicorn.workers.UvicornWorker`
but I'm getting a strange error I haven't found an answer to this error there:
```
django_1        | Traceback (most recent call last):
django_1        |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 376, in run_asgi
django_1        |     result = await app(self.scope, self.receive, self.send)
django_1        |   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/asgi2.py", line 6, in __call__
django_1        |     instance = self.app(scope)
django_1        | TypeError: __call__() missing 1 required positional argument: 'start_response'
django_1        | [2019-11-09 18:16:04 +0000] [36] [INFO] ('172.23.0.9', 50440) - "GET / HTTP/1.1" 500
django_1        | [2019-11-09 18:16:05 +0000] [36] [ERROR] Exception in ASGI application
django_1        | Traceback (most recent call last):
django_1        |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 376, in run_asgi
django_1        |     result = await app(self.scope, self.receive, self.send)
django_1        |   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/asgi2.py", line 6, in __call__
django_1        |     instance = self.app(scope)
django_1        | TypeError: __call__() missing 1 required positional argument: 'start_response'
django_1        | [2019-11-09 18:16:05 +0000] [36] [INFO] ('172.23.0.9', 50444) - "GET /favicon.ico HTTP/1.1" 500
django_1        | [2019-11-09 18:16:10 +0000] [36] [ERROR] Exception in ASGI application
django_1        | Traceback (most recent call last):
django_1        |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 376, in run_asgi
django_1        |     result = await app(self.scope, self.receive, self.send)
django_1        |   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/asgi2.py", line 6, in __call__
django_1        |     instance = self.app(scope)
django_1        | TypeError: __call__() missing 1 required positional argument: 'start_response'
django_1        | [2019-11-09 18:16:10 +0000] [36] [INFO] ('172.23.0.9', 50452) - "GET / HTTP/1.1" 500
django_1        | [2019-11-09 18:16:10 +0000] [36] [ERROR] Exception in ASGI application
django_1        | Traceback (most recent call last):
django_1        |   File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 376, in run_asgi
django_1        |     result = await app(self.scope, self.receive, self.send)
django_1        |   File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/asgi2.py", line 6, in __call__
django_1        |     instance = self.app(scope)
django_1        | TypeError: __call__() missing 1 required positional argument: 'start_response'
django_1        | [2019-11-09 18:16:10 +0000] [36] [INFO] ('172.23.0.9', 50456) - "GET /favicon.ico HTTP/1.1" 500
```

if it would be possible to guide me to find the most appropriate solution. Thank you in advance

**Comment by lovelydinosaur** [comment]
Uvicorn should be pointed at an ASGI app. It looks like you’re pointing it at a WSGI app “config.wsgi”.

I think Django Channels “Deploying with Uvicorn” docs should be able to guide you here.

**Comment by scwall** [comment]
Thank you for your answer, it works perfectly now, I replaced config.wsgi by my config.asgi. 
I didn't find help on django channels it is now just indicated: 

> Alternative Web Servers
> There are also alternative ASGI servers that you can use for serving Channels.
> 
> To some degree ASGI web servers should be interchangeable, they should all have the same basic functionality in terms of serving HTTP and WebSocket requests.
> 
> Aspects where servers may differ are in their configuration and defaults, performance characteristics, support for resource limiting, differing protocol and socket support, and approaches to process management.
> 
> You can see more alternative servers, such as Uvicorn, in the ASGI implementations documentation.

Thanks again for your help:)

**Comment by sainyamcc** [comment]
I still get this error : 
TypeError: __call__() missing 1 required positional argument: 'start_response'
Django 3.2, uvicorn = "^0.17.6"
I am running the command:
` gunicorn --bind 0.0.0.0:8004 myprofject.asgi -w 4 -k uvicorn.workers.UvicornWorker`
and here is the log, the startup is fine, but when I try to go to the url it spews out the error:

```
[2022-05-17 13:44:05 +0200] [68400] [INFO] Starting gunicorn 19.10.0
[2022-05-17 13:44:05 +0200] [68400] [INFO] Listening at: http://0.0.0.0:8004 (68400)
[2022-05-17 13:44:05 +0200] [68400] [INFO] Using worker: uvicorn.workers.UvicornWorker
/Users/maverick/.pyenv/versions/3.9.2/lib/python3.9/os.py:1023: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  return io.open(fd, *args, **kwargs)
[2022-05-17 13:44:05 +0200] [68401] [INFO] Booting worker with pid: 68401
[2022-05-17 13:44:05 +0200] [68402] [INFO] Booting worker with pid: 68402
[2022-05-17 13:44:05 +0200] [68403] [INFO] Booting worker with pid: 68403
[2022-05-17 13:44:05 +0200] [68404] [INFO] Booting worker with pid: 68404
[2022-05-17 11:44:07 +0000] [68401] [INFO] Started server process [68401]
[2022-05-17 11:44:07 +0000] [68401] [INFO] Waiting for application startup.
[2022-05-17 11:44:07 +0000] [68404] [INFO] Started server process [68404]
[2022-05-17 11:44:07 +0000] [68401] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2022-05-17 11:44:07 +0000] [68402] [INFO] Started server process [68402]
[2022-05-17 11:44:07 +0000] [68404] [INFO] Waiting for application startup.
[2022-05-17 11:44:07 +0000] [68402] [INFO] Waiting for application startup.
[2022-05-17 11:44:07 +0000] [68401] [INFO] Application startup complete.
[2022-05-17 11:44:07 +0000] [68404] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2022-05-17 11:44:07 +0000] [68402] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2022-05-17 11:44:07 +0000] [68403] [INFO] Started server process [68403]
[2022-05-17 11:44:07 +0000] [68402] [INFO] Application startup complete.
[2022-05-17 11:44:07 +0000] [68404] [INFO] Application startup complete.
[2022-05-17 11:44:07 +0000] [68403] [INFO] Waiting for application startup.
[2022-05-17 11:44:07 +0000] [68403] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2022-05-17 11:44:07 +0000] [68403] [INFO] Application startup complete.
[2022-05-17 11:44:09 +0000] [68403] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/Users/maverick/Library/Caches/pypoetry/virtualenvs/xyz-874my7h7-py3.9/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/maverick/Library/Caches/pypoetry/virtualenvs/xyz-874my7h7-py3.9/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/maverick/Library/Caches/pypoetry/virtualenvs/xyz-874my7h7-py3.9/lib/python3.9/site-packages/uvicorn/middleware/asgi2.py", line 16, in __call__
    instance = self.app(scope)
TypeError: __call__() missing 1 required positional argument: 'start_response'
[2022-05-17 11:44:10 +0000] [68402] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/Users/maverick/Library/Caches/pypoetry/virtualenvs/xyz-874my7h7-py3.9/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 366, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/maverick/Library/Caches/pypoetry/virtualenvs/xyz-874my7h7-py3.9/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/maverick/Library/Caches/pypoetry/virtualenvs/xyz-874my7h7-py3.9/lib/python3.9/site-packages/uvicorn/middleware/asgi2.py", line 16, in __call__
    instance = self.app(scope)
TypeError: __call__() missing 1 required positional argument: 'start_response'
```

**Comment by Evelynbarbosap** [comment]
had the same issue, somehow solved by rolling back my flask to version 2.1.3

**Comment by wakandan** [comment]
how do we solve this issue?

**Comment by developer992** [comment]
IS THERE A FIX FOR THIS OR EVEN EXPLANATION WHY IS IT HAPPENING

**Comment by CCXLV** [comment]
have the same issue
