### ISSUE TITLE
How do I run multiple servers gracefully in my code

### ISSUE THREAD

**Issue by whg517** [Kludex/uvicorn#541]
When my program was not developed as a web project, the web functionality was a submodule of the project. When multiple servers may need to be started in a project, such as server 1 using port 8080 for the rest API and server 2 using port 9090 for other things. Then my program controls the start of the loop.

However, I found that my code would not be executed after running `uvicorn.run` , and I could not arrange my tasks to the loop well.

Is there any elegant way to do it? I tried the following operations, but none of them could be solved well.

**1**

```
import uvicorn

loop = asyncio.get_event_loop()


async def app(scope, receive, send):
    ...


def s1():
    uvicorn.run("ttt:app", host="127.0.0.1", port=5005, log_level="info", loop='auto')


def s2():
    uvicorn.run("ttt:app", host="127.0.0.1", port=5006, log_level="info", loop='auto')


async def main():
    loop.call_soon(s1)


if __name__ == "__main__":
    loop.create_task(main())
    loop.run_forever()
```
It causes the following exception

```
/home/kevin/.virtualenvs/fastapi-7yP_jChR/bin/python /home/kevin/workspaces/develop/git/fastapi/ttt.py
ERROR:    Exception in callback s1() at /home/kevin/workspaces/develop/git/fastapi/ttt.py:12
handle: <Handle s1() at /home/kevin/workspaces/develop/git/fastapi/ttt.py:12>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/kevin/workspaces/develop/git/fastapi/ttt.py", line 13, in s1
    uvicorn.run("ttt:app", host="127.0.0.1", port=5005, log_level="info", loop='auto')
  File "/home/kevin/.virtualenvs/fastapi-7yP_jChR/lib/python3.6/site-packages/uvicorn/main.py", line 346, in run
    server.run()
  File "/home/kevin/.virtualenvs/fastapi-7yP_jChR/lib/python3.6/site-packages/uvicorn/main.py", line 374, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 471, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 425, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
INFO:     Started server process [19452]
INFO:     Uvicorn running on http://127.0.0.1:5005 (Press CTRL+C to quit)
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [19452]
```

**2**

```
import asyncio

import uvicorn

loop = asyncio.get_event_loop()


async def app(scope, receive, send):
    ...


def s1():
    uvicorn.run("ttt:app", host="127.0.0.1", port=5005, log_level="info", loop='auto')


async def main():
    loop.run_in_executor(None, s1)


if __name__ == "__main__":
    loop.create_task(main())
    loop.run_forever()
```

When I tried to run in a process, I found that I could not pass in the current loop because of the initialization loop in [`Config`](https://github.com/encode/uvicorn/blob/13094d9c98510237d8db2cf490130a08873ca491/uvicorn/config.py#L319).

And, output:

```
/home/kevin/.virtualenvs/fastapi-7yP_jChR/bin/python /home/kevin/workspaces/develop/git/fastapi/ttt.py
ERROR:    Future exception was never retrieved
future: <Future finished exception=RuntimeError("There is no current event loop in thread 'ThreadPoolExecutor-0_0'.",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/kevin/workspaces/develop/git/fastapi/ttt.py", line 13, in s1
    uvicorn.run("ttt:app", host="127.0.0.1", port=5005, log_level="info", loop='auto')
  File "/home/kevin/.virtualenvs/fastapi-7yP_jChR/lib/python3.6/site-packages/uvicorn/main.py", line 346, in run
    server.run()
  File "/home/kevin/.virtualenvs/fastapi-7yP_jChR/lib/python3.6/site-packages/uvicorn/main.py", line 373, in run
    loop = asyncio.get_event_loop()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 694, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/usr/local/lib/python3.6/asyncio/events.py", line 602, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
Traceback (most recent call last):
  File "/home/kevin/workspaces/develop/git/fastapi/ttt.py", line 22, in <module>
    loop.run_forever()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 438, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1415, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/local/lib/python3.6/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
```

---

My idea is that you can create multiple servers using twisted.

Is there any good operation or writing method? thank you

**Comment by euri10** [comment]
You can take a look at
https://github.com/encode/uvicorn/blob/a9fcfb7051757cfe25e7b289f829507133110f16/tests/test_main.py
in particular the last test

**Comment by indigoviolet** [comment]
```
class CustomServer(uvicorn.Server):
    def install_signal_handlers(self):
        pass

async def run_uvicorn():
    cfg = uvicorn.Config(api, loop="none", lifespan="off")
    server = CustomServer(cfg)
    await server.serve()
```
Leaving this here for future reference, the docs are lacking around this form of usage, took some digging through (to be fair, very clean) code to figure it out.

**Comment by lovelydinosaur** [comment]
I'll close this off as a usage question. Certainly scope for improved docs, tho beyond my available bandwidth right now.
