### ISSUE TITLE
Ubuntu 18.04+cpython3.6.8+pipenv okay. pypy3.6.9 throws "TypeError: 'NoneType' object is not iterable"

### ISSUE THREAD

**Issue by amimoto** [Kludex/uvicorn#543]
Using Ubuntu 18.04, pipenv and pypy3.6.9 ends up failing with the error `TypeError: 'NoneType' object is not iterable`. Using cPython 3.6.8 works fine. Pypy 3.6.9 comes from https://launchpad.net/~pypy/+archive/ubuntu/ppa

Thrashing about for ideas, also tried out `uvicorn=0.8.6` but that didn't seem to help.

Using the example files from `uvloop` generally worked (echoserver yielded an error but that was more that the example wasn't compatible with 3.6 issue than this).

Am I doing something wrong? I've only started using pypy recently so perhaps I've got something funky in my assumptions and the way I'm doing things.

Steps I used from command line:

```bash
mkdir uvicorn-test
cd uvicorn-test
pipenv install --python `which pypy3`
pipenv shell
pipenv install uvicorn
echo > example.py
  Pasted example code from quickstart: https://www.uvicorn.org/#quickstart
  then Control-D
uvicorn example:app
```

Log of output trying to use `pypy3.6.9`

```bash
aki@nexus:~/apptest$ mkdir uvicorn-test
aki@nexus:~/apptest$ cd uvicorn-test/
aki@nexus:~/apptest/uvicorn-test$ pipenv install --python `which pypy3`
Creating a virtualenv for this project…
Pipfile: /home/aki/apptest/uvicorn-test/Pipfile
Using /usr/bin/pypy3 (3.6.9) to create virtualenv…
⠋ Creating virtual environment...Already using interpreter /usr/bin/pypy3
Using base prefix '/usr/lib/pypy3'
  No LICENSE.txt / LICENSE found in source
New pypy executable in /home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/bin/pypy3
Also creating executable in /home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/bin/pypy
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /usr/bin/pypy3
✔ Successfully created virtual environment!
Virtualenv location: /home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk
Creating a Pipfile for this project…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (ca72e7)!
Installing dependencies from Pipfile.lock (ca72e7)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
aki@nexus:~/apptest/uvicorn-test$ pipenv shell
Launching subshell in virtual environment…
aki@nexus:~/apptest/uvicorn-test$  . /home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/bin/activate
(uvicorn-test) aki@nexus:~/apptest/uvicorn-test$ pipenv install uvicorn
Installing uvicorn…
✔ Installation Succeeded
Pipfile.lock (6ed322) out of date, updating to (ca72e7)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (6ed322)!
Installing dependencies from Pipfile.lock (6ed322)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 6/6 — 00:00:07
(uvicorn-test) aki@nexus:~/apptest/uvicorn-test$ cat > example.py
async def app(scope, receive, send):
    assert scope['type'] == 'http'
    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ]
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })
(uvicorn-test) aki@nexus:~/apptest/uvicorn-test$ uvicorn example:app
INFO:     Started server process [21882]
Traceback (most recent call last):
  File "/home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/site-packages/uvicorn/main.py", line 323, in main
    run(**kwargs)
  File "/home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/site-packages/uvicorn/main.py", line 346, in run
    server.run()
  File "/home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/site-packages/uvicorn/main.py", line 374, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
TypeError: 'NoneType' object is not iterable
(uvicorn-test) aki@nexus:~/apptest/uvicorn-test$
```

Log of successful cPython run:

```bash
aki@nexus:~/apptest$ rm -rf uvicorn-test
aki@nexus:~/apptest$ mkdir uvicorn-test
aki@nexus:~/apptest$ cd uvicorn-test/
aki@nexus:~/apptest/uvicorn-test$ pipenv install --python `which python3`
Virtualenv already exists!
Removing existing virtualenv…
Creating a virtualenv for this project…
Pipfile: /home/aki/apptest/uvicorn-test/Pipfile
Using /usr/bin/python3 (3.6.8) to create virtualenv…
⠼ Creating virtual environment...Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/bin/python3
Also creating executable in /home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/bin/python
Installing setuptools, pip, wheel...
done.
✔ Successfully created virtual environment!
Virtualenv location: /home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk
Creating a Pipfile for this project…
Pipfile.lock not found, creating…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
Updated Pipfile.lock (ca72e7)!
Installing dependencies from Pipfile.lock (ca72e7)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 0/0 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
aki@nexus:~/apptest/uvicorn-test$ pipenv shell
Launching subshell in virtual environment…
aki@nexus:~/apptest/uvicorn-test$  . /home/aki/.local/share/virtualenvs/uvicorn-test-FCyCddYk/bin/activate
(uvicorn-test) aki@nexus:~/apptest/uvicorn-test$ pipenv install uvicorn
Installing uvicorn…
✔ Installation Succeeded
Pipfile.lock (6ed322) out of date, updating to (ca72e7)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…
✔ Success!
Updated Pipfile.lock (6ed322)!
Installing dependencies from Pipfile.lock (6ed322)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 6/6 — 00:00:02
(uvicorn-test) aki@nexus:~/apptest/uvicorn-test$ cat > example.py
async def app(scope, receive, send):
    assert scope['type'] == 'http'
    await send({
        'type': 'http.response.start',
        'status': 200,
        'headers': [
            [b'content-type', b'text/plain'],
        ]
    })
    await send({
        'type': 'http.response.body',
        'body': b'Hello, world!',
    })
(uvicorn-test) aki@nexus:~/apptest/uvicorn-test$ uvicorn example:app
INFO:     Started server process [22034]
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
```

**Comment by euri10** [comment]
You might be interested in [this](https://github.com/MagicStack/uvloop/issues/303) uvloop doesn't support pypy and is likely to be slower anyway

**Comment by amimoto** [comment]
Thanks for the note. I didn't realize uvloop's reliance on cython and you're right, the [pypy3 test appears to take longer than cpython](https://travis-ci.org/encode/uvicorn) though perhaps it's merely JIT getting warmed up.

My needs are met so I'm happy to close this note. However, seeing as there's a pypy3 test in the tests, perhaps I'll leave it here for the devs to decide what they wish to do. Please feel free to close this ticket or let me know if I can be of any futher assistance.

**Comment by abersheeran** [comment]
I used a hello world, tested pypy3 and python3.7, and found that PyPy is not as fast as using httptools + uvloop.

The speed of the former is only 1/6 to 1/7 of the latter.

**Comment by florimondmanca** [comment]
Closing as it seems this question has been resolved. :-)
