### ISSUE TITLE
Cryptic Traceback printed every few minutes

### ISSUE THREAD

**Issue by 2m** [Kludex/uvicorn#547]
We are seeing this traceback every five minutes.
```
Traceback (most recent call last): File "/usr/local/bin/uvicorn", line 8, in <module> sys.exit(main()) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__ return self.main(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main rv = self.invoke(ctx) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke return ctx.invoke(self.callback, **ctx.params) File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke return callback(*args, **kwargs) File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 323, in main run(**kwargs) File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 346, in run server.run() File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 374, in run loop.run_until_complete(self.serve(sockets=sockets)) File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete File "/usr/local/lib/python3.8/site-packages/uvicorn/main.py", line 381, in serve
```

However the process is not being restarted.

The message is a bit cryptic, as I can not see what is the exception that is being thrown.

We are running the latest uvicorn `0.11.1` to serve Django `3.0.2` app.

**Comment by lovelydinosaur** [comment]
Did you make any progress on this?
Not a lot I'm able to do, since there's no full traceback here, no way of replicating the issue, and not any obvious cases of other reporters chiming in with something similar.
Is it being raised intermintely, or reliably on 5 minute cycles?
Are you able to reduce it down to a small reproducible case in any way?

**Comment by 2m** [comment]
I do not see this anymore in our production environment. Not really sure when it stopped printing this. So I guess we can close this. :)
