### ISSUE TITLE
uvloop version issue

### ISSUE THREAD

**Issue by rodneykeeling** [Kludex/uvicorn#559]
Hi,

After running `pip install uvicorn==0.11.2`, I see that it installs `uvloop==0.14.0` as a dependency. However, when running `uvicorn`, I get this error:

```
> uvicorn api:app --reload      
Traceback (most recent call last):
  File "/home/rodney/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/home/rodney/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/rodney/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 783, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (uvloop 0.14.0 (/home/rodney/.pyenv/versions/3.7.0/lib/python3.7/site-packages), Requirement.parse('uvloop==0.12.*'), {'uvicorn'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rodney/.pyenv/versions/3.7.0/bin/uvicorn", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/rodney/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/home/rodney/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/home/rodney/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/rodney/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 576, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/rodney/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 589, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/rodney/.pyenv/versions/3.7.0/lib/python3.7/site-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'uvloop==0.12.*' distribution was not found and is required by uvicorn
```

It looks like there's still something depending on `uvloop==0.12`?

However, if I `pip uninstall uvloop` and `pip install uvloop==0.12`, I get a dependency error:
```
ERROR: uvicorn 0.11.2 has requirement uvloop>=0.14.0; sys_platform != "win32" and sys_platform != "cygwin" and platform_python_implementation != "pypy", but you'll have uvloop 0.12.0 which is incompatible.
```

**Comment by rodneykeeling** [comment]
My mistake, there was a python version conflict with pyenv.

**Comment by roulpriya** [comment]
I am getting the same error. How you rectified it?
