### ISSUE TITLE
Invalid argument was supplied error on windows

### ISSUE THREAD

**Issue by SubCoder1** [Kludex/uvicorn#683]
There seems to be an issue when I increase the worker process count greater than 1.
**command** -> `uvicorn --port 9000 --workers 2 MyProject.asgi:application`
**error log** ->
```
INFO:     Uvicorn running on http://127.0.0.1:9000 (Press CTRL+C to quit)
INFO:     Started parent process [17696]
INFO:     Started server process [20428]
INFO:     Started server process [15476]
INFO:     Waiting for application startup.
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Application startup complete.
Process SpawnProcess-2:
Traceback (most recent call last):
  File "c:\users\arnab\appdata\local\programs\python\python37-32\Lib\multiprocessing\process.py", line 297, in _bootstrap    
    self.run()
  File "c:\users\arnab\appdata\local\programs\python\python37-32\Lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "t:\my projects\scholify-web\env\lib\site-packages\uvicorn\subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "t:\my projects\scholify-web\env\lib\site-packages\uvicorn\main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\arnab\appdata\local\programs\python\python37-32\Lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "t:\my projects\scholify-web\env\lib\site-packages\uvicorn\main.py", line 399, in serve
    await self.startup(sockets=sockets)
  File "t:\my projects\scholify-web\env\lib\site-packages\uvicorn\main.py", line 433, in startup
    create_protocol, sock=sock, ssl=config.ssl, backlog=config.backlog
  File "c:\users\arnab\appdata\local\programs\python\python37-32\Lib\asyncio\base_events.py", line 1393, in create_server    
    server._start_serving()
  File "c:\users\arnab\appdata\local\programs\python\python37-32\Lib\asyncio\base_events.py", line 282, in _start_serving    
    sock.listen(self._backlog)
OSError: [WinError 10022] An invalid argument was supplied
```

**Comment by euri10** [comment]
this one has a fix I really dont understand

**Comment by qqletter** [comment]
I get the same error when use multiple workers on win11(22H2) and uvicorn 0.22.0.
It seems the error only appears when use workers=2

**Comment by Kludex** [comment]
Please check the current open issues instead of commenting on a 3 years old issue that was solved.
