### ISSUE TITLE
AttributeError: 'uvloop.loop.TCPTransport' object has no attribute 'drain'

### ISSUE THREAD

**Issue by parisk** [Kludex/uvicorn#70]
Hi there,

First of all, congratulations for Uvicorn — it's truly amazing and pleasant to use!

Today I was messing around with Django 2.0 + Channels and thought about giving Uvicorn a try as a replacement for Daphne.

Although everything seems to work like a charm, I see an `AttributeError` in my server's log, without this exception surfacing to the browser. It seems to be caused by the following piece of code:

https://github.com/encode/uvicorn/blob/24bf63f5c6e1f3fa226e417b89f4e4d32ffa26e4/uvicorn/protocols/http.py#L154-L157

Providing some more details below (full traceback + Python package + system details)

## Traceback

```python
Not Found: /favicon.ico
Task exception was never retrieved
future: <Task finished coro=<AsgiHandler.__call__() done, defined at /mnt/data/.python-3.6/lib/python3.6/site-packages/channels/http.py:172> exception=AttributeError("'uvloop.loop.TCPTransport' object has no attribute 'drain'",)>
Traceback (most recent call last):
  File "/mnt/data/.python-3.6/lib/python3.6/site-packages/channels/http.py", line 190, in __call__
    await self.handle(body)
  File "/mnt/data/.python-3.6/lib/python3.6/site-packages/asgiref/sync.py", line 110, in __call__
    return await asyncio.wait_for(future, timeout=None)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 339, in wait_for
    return (yield from fut)
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/mnt/data/.python-3.6/lib/python3.6/site-packages/asgiref/sync.py", line 125, in thread_handler
    return self.func(*args, **kwargs)
  File "/mnt/data/.python-3.6/lib/python3.6/site-packages/channels/http.py", line 226, in handle
    self.send(response_message)
  File "/mnt/data/.python-3.6/lib/python3.6/site-packages/asgiref/sync.py", line 64, in __call__
    return call_result.result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/mnt/data/.python-3.6/lib/python3.6/site-packages/asgiref/sync.py", line 78, in main_wrap
    result = await self.awaitable(*args, **kwargs)
  File "/mnt/data/.python-3.6/lib/python3.6/site-packages/uvicorn/protocols/http.py", line 158, in send
    await self.transport.drain()
AttributeError: 'uvloop.loop.TCPTransport' object has no attribute 'drain'
```

## `pip freeze`

```
asgiref==2.3.0
async-timeout==2.0.1
attrs==17.4.0
autobahn==18.4.1
Automat==0.6.0
backcall==0.1.0
cffi==1.11.5
channels==2.1.1
constantly==15.1.0
daphne==2.1.1
decorator==4.3.0
dj-database-url==0.5.0
Django==2.0
djangorestframework==3.8.2
gunicorn==19.8.1
httptools==0.0.11
hyperlink==18.0.0
idna==2.6
incremental==17.5.0
ipython==6.3.1
ipython-genutils==0.2.0
jedi==0.12.0
parso==0.2.0
pexpect==4.5.0
pickleshare==0.7.4
prompt-toolkit==1.0.15
psycopg2-binary==2.7.4
ptyprocess==0.5.2
pycparser==2.18
Pygments==2.2.0
pytz==2017.3
sec==0.2.2
simplegeneric==0.8.1
six==1.11.0
traitlets==4.3.2
Twisted==18.4.0
txaio==2.10.0
uvicorn==0.1.1
uvloop==0.9.1
wcwidth==0.1.7
websockets==4.0.1
whitenoise==3.3.1
zope.interface==4.5.0
```

## System details

- **OS**: Ubuntu 16.04 / [SourceLair](https://www.sourcelair.com)
- **Python version**: 3.6.4
- **pip version**: 10.0.1

**Comment by zeromake** [comment]
should is uvloop not implements drain function, [UVStream](https://github.com/MagicStack/uvloop/blob/master/uvloop/handles/stream.pyx#L208).

UVStream implements [asyncio-stream](https://docs.python.org/3/library/asyncio-stream.html) but not has  drain function.

**Comment by lovelydinosaur** [comment]
Okay, I guess it might be worth opening up an issue with the MagicStack team to see if they'd consider implementing that part of the API.

**Comment by lovelydinosaur** [comment]
Rejigged in 0.2, should resolve this issue.
