### ISSUE TITLE
Unable to use uvicorn with cython modules

### ISSUE THREAD

**Issue by elben10** [Kludex/uvicorn#747]
### Checklist

- [x] The bug is reproducible against the latest release and/or `master`.
- [x] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I am not able to import cython modules when I use uvicorn, but if I use gunicorn with the `UvicornH11Worker` class everything works as expected

### To reproduce

Is described in the following [repo](https://github.com/elben10/fastapi_cython_bug)
### Expected behavior

Be able to import the cython module

### Actual behavior

Uvicorn crashes

![](https://github.com/elben10/fastapi_cython_bug/raw/master/images/screenshot.png)

### Debugging material

Running uvicorn 0.11.8 with CPython 3.8.2 on Darwin

<details>
  <summary>Click to expand tracelog</summary>
  
```python
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/Users/jakobjulelben/Library/Python/3.8/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jakobjulelben/Library/Python/3.8/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jakobjulelben/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jakobjulelben/Library/Python/3.8/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/main.py", line 345, in main
    run(**kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/main.py", line 369, in run
    server.run()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/main.py", line 397, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/main.py", line 404, in serve
    config.load()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/config.py", line 278, in load
    self.loaded_app = import_from_string(self.app)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 3, in <module>
    from fastapi_cython_bug import module
ImportError: dlopen(./fastapi_cython_bug/module.cpython-38-darwin.so, 2): no suitable image found.  Did find:
        file system relative paths not allowed in hardened programs
```
</details>

### Environment

- OS / Python / Uvicorn version: just run `uvicorn --version`
- uvicorn main:app

### Additional context

No additional context.

**Comment by euri10** [comment]
thanks for the detailed submission and repo, unfortunately this work fine for me under linux as you can see below

So my best guess would be that it has to do with mac os and where cython compiled files are located given the error message but I'm not knowledgeable enough on that front to be quite certain about it.

Find below a screen of the various compiled files.

So I will close now as nothing indicates this could be a uvicorn's issue but feel free to re-open if you think that's a wrong statement.


```
creating build
creating build/temp.linux-x86_64-3.8
creating build/temp.linux-x86_64-3.8/fastapi_cython_bug
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/lotso/PycharmProjects/fastapi_cython_bug/venv/include -I/home/lotso/.asdf/installs/python/3.8.5/include/python3.8 -c fastapi_cython_bug/module.c -o build/temp.linux-x86_64-3.8/fastapi_cython_bug/module.o
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/fastapi_cython_bug
gcc -pthread -shared -L/home/lotso/.asdf/installs/python/3.8.5/lib -L/home/lotso/.asdf/installs/python/3.8.5/lib build/temp.linux-x86_64-3.8/fastapi_cython_bug/module.o -o build/lib.linux-x86_64-3.8/fastapi_cython_bug/module.cpython-38-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.8/fastapi_cython_bug/module.cpython-38-x86_64-linux-gnu.so -> fastapi_cython_bug
❯ uvicorn main:app
INFO:     Started server process [13742]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:46866 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:46866 - "GET /favicon.ico HTTP/1.1" 404 Not Found
```

I  can get the cython hello world result in an endpont with : 


```
from fastapi import FastAPI

from fastapi_cython_bug import module

app = FastAPI()

@app.get("/")
async def use_hello():
    return module.hello_world()
```
```
❯ uvicorn main:app
INFO:     Started server process [14866]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
^[[AINFO:     127.0.0.1:46900 - "GET / HTTP/1.1" 200 OK
```
![20200808_1835_950x330_1596904537](https://user-images.githubusercontent.com/1104190/89715505-46921a00-d9a6-11ea-8684-29c3e1c47312.png)
