### ISSUE TITLE
Error messages when starting server with multiple workers

### ISSUE THREAD

**Issue by mp3cko** [Kludex/uvicorn#775]
### Checklist

- [X] The bug is reproducible against the latest release and/or `master`.
- [X] There are no similar issues or pull requests to fix it yet.

### Describe the bug

When running my app that uses fastAPI (and starlette) with uvicorn using --workers argument I get a huge traceback but the app starts eventually

### Expected behavior

Server starting normally

### Actual behavior

Slow boot-up time and a huge traceback (depending on amount of workers)

### Debugging material

```
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started parent process [16824]
INFO:     Started server process [4000]
INFO:     Waiting for application startup.       
INFO:     Application startup complete.
INFO:     Started server process [18016]
INFO:     Waiting for application startup.       
INFO:     Started server process [6768] 
INFO:     Application startup complete.
INFO:     Waiting for application startup.       
Process SpawnProcess-1:
INFO:     Application startup complete.
Process SpawnProcess-2:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "C:\Program Files (x86)\Python38-32\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "C:\Program Files (x86)\Python38-32\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Program Files (x86)\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\subprocess.py", line 62, in subprocess_started
    target(sockets=sockets)
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\main.py", line 407, in serve
    await self.startup(sockets=sockets)
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\main.py", line 390, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\main.py", line 440, in startup
    server = await loop.create_server(
  File "C:\Program Files (x86)\Python38-32\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Program Files (x86)\Python38-32\lib\asyncio\base_events.py", line 1484, in create_server
    server._start_serving()
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\main.py", line 407, in serve
    await self.startup(sockets=sockets)
  File "C:\Program Files (x86)\Python38-32\lib\asyncio\base_events.py", line 313, in _start_serving
    sock.listen(self._backlog)
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\main.py", line 440, in startup
    server = await loop.create_server(
OSError: [WinError 10022] An invalid argument was supplied
  File "C:\Program Files (x86)\Python38-32\lib\asyncio\base_events.py", line 1484, in create_server
    server._start_serving()
  File "C:\Program Files (x86)\Python38-32\lib\asyncio\base_events.py", line 313, in _start_serving
    sock.listen(self._backlog)
OSError: [WinError 10022] An invalid argument was supplied
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<LifespanOn.main() running at c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\lifespan\on.py:48> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x04C95238>()]>>
--- Logging error ---
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<LifespanOn.main() running at c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\lifespan\on.py:48> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x04116238>()]>>
Traceback (most recent call last):
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\lifespan\on.py", line 48, in main
    await app(scope, self.receive, self.send)
--- Logging error ---
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\logging\__init__.py", line 1081, in emit
    msg = self.format(record)
  File "C:\Program Files (x86)\Python38-32\lib\logging\__init__.py", line 925, in format
    return fmt.format(record)
  File "C:\Program Files (x86)\Python38-32\lib\logging\__init__.py", line 667, in format
    s = self.formatMessage(record)
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\logging.py", line 48, in formatMessage
    recordcopy = copy(record)
  File "C:\Program Files (x86)\Python38-32\lib\copy.py", line 92, in copy
    rv = reductor(4)
ImportError: sys.meta_path is None, Python is likely shutting down
Call stack:
Traceback (most recent call last):
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\lifespan\on.py", line 59, in main
    self.logger.error(msg, exc_info=exc)
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\lifespan\on.py", line 48, in main
    await app(scope, self.receive, self.send)
GeneratorExit
Message: "Exception in 'lifespan' protocol\n"
Arguments: ()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python38-32\lib\logging\__init__.py", line 1081, in emit
    msg = self.format(record)
  File "C:\Program Files (x86)\Python38-32\lib\logging\__init__.py", line 925, in format
    return fmt.format(record)
  File "C:\Program Files (x86)\Python38-32\lib\logging\__init__.py", line 667, in format
    s = self.formatMessage(record)
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\logging.py", line 48, in formatMessage
    recordcopy = copy(record)
  File "C:\Program Files (x86)\Python38-32\lib\copy.py", line 92, in copy
    rv = reductor(4)
ImportError: sys.meta_path is None, Python is likely shutting down
Call stack:
  File "c:\users\mario\.virtualenvs\fastapi-kcmwlcl6\lib\site-packages\uvicorn\lifespan\on.py", line 59, in main
    self.logger.error(msg, exc_info=exc)
Message: "Exception in 'lifespan' protocol\n"
Arguments: ()
```

### Environment

- OS / Python / Uvicorn version: just run `uvicorn --version`

win10 1909
cpython 3.8.5 (32bit)
uvicorn 0.11.8 

- The exact command you're running uvicorn with, all flags you passed included. If you run it with gunicorn please do the same. If there is a reverse-proxy involved and you cannot reproduce without it please give the minimal config of it to reproduce.

uvicorn main:app --workers 100

**Comment by euri10** [comment]
hi @Maracko , do you really have 100 cores ?

**Comment by mp3cko** [comment]
Hey, 
I most definitely don't. Didn't know those were actually processes that should be mapped to the amount of cores, I thought those were threads 😅.

However I have 4 cores on my laptop and even if I run it with `--workers 3` argument for example the same thing happens.

**Comment by euri10** [comment]
Can you paste your lifespan handler, it looks like there's something going
on there?
Do you have the same behavior without nthe workers flag ?

**Comment by mp3cko** [comment]
I don't get any traceback or errors when running without the workers flag.

> Can you paste your lifespan handler, it looks like there's something going on there?

Could you please elaborate on that?

**Comment by euri10** [comment]
A Lifespan exception occured given the logs you sent, can you paste a minimal reproductible example please ?

**Comment by mp3cko** [comment]
I don't have any special functions or methods for handling lifespan (all I know is that it is a protocol).

Since it's production code I don't wanna paste it here, but if you could give me any hints on something specific that could help you I can probably make something work.

Also thanks for helping me out.

**Comment by euri10** [comment]
hello @Maracko I'll close this for housekeeping purposes, don't hesitate to reopen with more insights so that's actionnable, in the current state we're missing info to be able to reproduce your issue
