### ISSUE TITLE
New Uvicorn version running with Gunicorn handles an error missing uvloop module

### ISSUE THREAD

**Issue by alxgithub** [Kludex/uvicorn#795]
Hi,

The new version of Uvicorn running with Gunicorn gives an error saying that the uvloop is missing. Here's the stack-trace:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.7/site-packages/uvicorn/workers.py", line 60, in init_process
    self.config.setup_event_loop()
  File "/usr/local/lib/python3.7/site-packages/uvicorn/config.py", line 333, in setup_event_loop
    loop_setup = import_from_string(LOOP_SETUPS[self.loop])
  File "/usr/local/lib/python3.7/site-packages/uvicorn/importer.py", line 23, in import_from_string
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.7/site-packages/uvicorn/loops/uvloop.py", line 3, in <module>
    import uvloop
ModuleNotFoundError: No module named 'uvloop'
```

I saw that 3 days ago you've changed the installation requirements, so the default way `pip install uvicorn` will install the minimum and if we need uvloop, we need to change to `pip install uvicorn[standard]`.

So this means that to use the UvicornWorker with Gunicorn we need to install the standard or is this a bug?

MI'm using Python 3.7 and my setup file has:
```
'gunicorn>=20.0.4,<21.0',
...
'uvicorn>=0.11.3,<1.0',
```

Thanks!

**Comment by euri10** [comment]
Yep use the standard extra to get uvloop, using gunicorn has nothing to do with the loop used

**Comment by alxgithub** [comment]
Thanks!

**Comment by udiNur** [comment]
it's was weird that after the libs update my server stop from working because the uvloop is not anymore in the requirements.txt, even that it's necessary by default on GCP and mac.

it's taken me a bit of time to figure this out because of the uvloop was already installed over my local env (because of version 0.11.08)

I didn't understand why it's now not part of the requirements anymore... I will be happy to understand it because I'm probably missing something.

thanks for the awesome lib!!
