### ISSUE TITLE
Issue using unicorn with --reload flag

### ISSUE THREAD

**Issue by JosiasAurel** [Kludex/uvicorn#798]
### Checklist

- [✓ ] The bug is reproducible against the latest release and/or `master`.
- [ ] There are no similar issues or pull requests to fix it yet.

### Describe the bug

I installed FastAPI and I am using unicorn as ASGI server . When running the app as follows
```shell
$ unicorn main:app
```
It works but when I add the reload flag, it crashes with the error : 
```shell
ModuleNotFoundError: No module named '_posixshmem'
```

### To reproduce

Here is the app code : 
```python 
from typing import Optional

from fastapi import FastAPI

app = FastAPI()


@app.get("/")
def read_root():
    return {"Hello": "World"}


@app.get("/items/{item_id}")
def read_item(item_id: int, q: Optional[str] = None):
    return {"item_id": item_id, "q": q}
```
### Expected behavior

```bash
$ uvicorn main:app --reload

INFO: Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO: Started reloader process [28720]
INFO: Started server process [28722]
INFO: Waiting for application startup.
INFO: Application startup complete.
```
### Debugging material

Tracebacks : 
```bash
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
error walking file system: FileNotFoundError [Errno 2] No such file or directory: '/data/data/com.termux/files/home/storage/music'
INFO:     Started reloader process [24743] using watchgod
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/uvicorn/main.py", line 355, in main
    run(**kwargs)
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/uvicorn/main.py", line 373, in run
    supervisor.run()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/uvicorn/supervisors/basereload.py", line 34, in run
    self.startup()
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/uvicorn/supervisors/basereload.py", line 55, in startup
    self.process.start()
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 39, in _launch
    from . import resource_tracker
  File "/data/data/com.termux/files/usr/lib/python3.8/multiprocessing/resource_tracker.py", line 38, in <module>
    import _posixshmem
ModuleNotFoundError: No module named '_posixshmem'
```
### Environment

- OS / Python / Uvicorn version: just run `uvicorn --version`
- The exact command you're running uvicorn with, all flags you passed included. If you run it with gunicorn please do the same. If there is a reverse-proxy involved and you cannot reproduce without it please give the minimal config of it to reproduce.
Unicorn Version ```Running uvicorn 0.12.1 with CPython 3.8.5 on Linux```

**Comment by euri10** [comment]
Can you reproduce in a clean virtual env ?

**Comment by JosiasAurel** [comment]
Here is the link to the repo [here](https://github.com/JosiasAurel/FastAPI-uvicorn-issue-err)

**Comment by euri10** [comment]
> Here is the link to the repo [here](https://github.com/JosiasAurel/FastAPI-uvicorn-issue-err)

the link provided has nothing to do with websockets ?
I'll close for now as not reproducible, I suspect you may have a broken virtual env, there's no indication there's an issue with uvicorn here,
feel free to reopen with precise enough information,

**Comment by victoraugustolls** [comment]
Just an observation: I started having the same issue when running with "watchgod" so I just removed it and reload started working. This means that I don't install uvicorn with the standard flag, but manually install httptools and uvloop.
